---
title: "7 - Beta diversity"
output: html_notebook
---
# COPD vs control
## PERMANOVA
```{r}
# There are two tests that are widely used in beta diversity analyses: betadisper and adonis. 
# Betadisper tests whether two or more groups are homogeneously dispersed in relation to their species in studied samples (it is a multivariate analogue of Levene's test for homogeneity of variances). This test can be done to see if one group has more compositional variance than another. Moreover, homogeneity of dispersion among groups is very advisable to have if you want to test if two or more groups have different compositions, which is tested by adonis. So firstly I will perform betadisper: then move onto adonis
# Use betadisper to assess homogeneity of group dispersions - it first calculates the average distance of group members to the group centroid in multivariate space (generated by a distance matrix). Then, an ANOVA is done to test if the dispersions (variances) of groups are different.
#Extract abundance matrix from phyloseq object
ARGclusters.for.beta.div <- as(otu_table(ARGcluster.aggl), "matrix")
# transform into a data frame
ARG.cluster.dataframe <-as.data.frame(ARGclusters.for.beta.div)
ARG.cluster.dataframe
# Calculate BC distances between all sample types
BC.distances <- vegdist(ARG.cluster.dataframe, method =  "bray")
# Add column to dataframe to include Copdcaco status
ARG.cluster.dataframe$copdcaco <- ARGcluster.aggl@sam_data$copdcaco
head(ARG.cluster.dataframe)

# Betadisper 
Betadisper.ARGcluster.copdcontrolblank <- betadisper(BC.distances, ARG.cluster.dataframe$copdcaco)
Betadisper.ARGcluster.copdcontrolblank
# Perform an anova using the group dispersions.
Anova.betadisper.copdcontrolblank <- anova(Betadisper.ARGcluster.copdcontrolblank)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous ("Null hypothesis of no difference in dispersion between groups
Anova.betadisper.copdcontrolblank$`Pr(>F)`# to add to PCoA in above chunk
# make a plot to see our first two PCoA axes to see how our data fits there:
plot(Anova.betadisper.copdcontrolblank)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# PERMANOVA
# Use adonis2 to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
Permanova_results_COPDcontrolblank <- adonis2(BC.distances~ ARG.cluster.dataframe$copdcaco, permutations = 999)
# we see that the groups do  have significantly different compositions (p<0.05). 
# We can conclude that our groups (COPD and control and blank) present homogeneity among group dispersions (compositions vary similarly) but that they have different  compositions.

# Now repeat with no blanks (this is likely the cause of the observed difference in composition)
ARGclusters.for.beta.div <- as(otu_table(ARGcluster.aggl), "matrix")
ARG.cluster.dataframe.noblanks <-as.data.frame(ARGclusters.for.beta.div)[-c(70, 71, 72),] # Remove blanks from the df

# Calculate the BC distances between COPD case and control only
BC.distances.noblanks <- vegdist(ARG.cluster.dataframe.noblanks, method =  "bray")
# Add column to dataframe to include Copdcaco status
ARG.cluster.dataframe.noblanks$copdcaco <- ARGcluster.aggl.noblanks@sam_data$copdcaco
head(ARG.cluster.dataframe.noblanks)

# Betadisper 
Betadisper.ARGcluster.COPDcaco <- betadisper(BC.distances.noblanks, ARG.cluster.dataframe.noblanks$copdcaco)
Betadisper.ARGcluster.COPDcaco
# Perform an anova using the group dispersions.
Anova_betadisper <- anova(Betadisper.ARGcluster.COPDcaco)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous ("Null hypothesis of no difference in dispersion between groups
Anova_betadisper$`Pr(>F)`# to add to PCoA in above chunk
# make a plot to see our first two PCoA axes to see how our data fits there:
plot(Betadisper.ARGcluster.COPDcaco)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# PERMANOVA
# Use adonis2 to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
Permanova_results_COPDcontrol<- adonis2(BC.distances.noblanks~ ARG.cluster.dataframe.noblanks$copdcaco, permutations = 999)
# we see that the groups do not have significantly different compositions (p>0.05). 
# We can conclude that our groups (COPD and control) present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions.
```
## PCoA ordinations
```{r}
# PCoA plot
set.seed(123)
Permanova_results_COPDcontrol <- adonis2(BC.distances.noblanks~ ARG.cluster.dataframe.noblanks$copdcaco, permutations = 999)
Permanova_pval_COPDcontrol <- Permanova_results_COPDcontrol$`Pr(>F)`[1]
# p-value = 0.19 - no significant differences in group centroids-  We can conclude that our groups

# Create PCoA for manuscript
# Firstly I will rename the codes "1", "0" as COPD & control 
ARGcluster.aggl.noblanks@sam_data$copdcaco <- revalue(ARGcluster.aggl.noblanks@sam_data$copdcaco, c('1' ='COPD', '0' = 'control'))

ARGcluster.aggl.PCoA.noblanks.ordination <- ordinate(ARGcluster.aggl.noblanks, method="PCoA", distance="bray")

ARGcluster.aggl.PCoA.plot.noblanks <- plot_ordination(ARGcluster.aggl.noblanks, ARGcluster.aggl.PCoA.noblanks.ordination, color = "copdcaco", shape = "copdcaco") +
  ggtitle("Bray-Curtis PCoA - COPD vs control") +
  labs(legend = "COPD/control status") +
  geom_point(aes(color = copdcaco), size = 4) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  geom_text(aes(label = row.names(ARGcluster.aggl.noblanks@sam_data), hjust = -0.3, vjust = -0.5), size = 2) +
  theme(
    plot.title = element_text(size = 12),
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 15),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10)
  ) +
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = copdcaco, color = copdcaco)) +
  scale_fill_manual(values = c("cornflowerblue", "orange")) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  geom_text(x = 0.42, y = -0.47, label = paste("PERMANOVA, p-value =", Permanova_pval_COPDcontrol), size = 4, color = "black", family = "Arial") +
  xlab("PCoA1") +
  ylab("PCoA2") +
  coord_fixed(ratio = 1) +
  guides(color = guide_legend(title = "Study population"))

ggsave("Output_files//PCoAs//ARGcluster.aggl.PCoA.plot.noblanks.png", ARGcluster.aggl.PCoA.plot.noblanks, width = 8, height = 6, dpi = 3000)
```
# Livestock exposure
## PERMANOVA
```{r}
# There are two tests that are widely used in beta diversity analyses: betadisper and adonis. 
# Betadisper tests whether two or more groups are homogeneously dispersed in relation to their species in studied samples (it is a multivariate analogue of Levene's test for homogeneity of variances). This test can be done to see if one group has more compositional variance than another. Moreover, homogeneity of dispersion among groups is very advisable to have if you want to test if two or more groups have different compositions, which is tested by adonis. So firstly I will perform betadisper: then move onto adonis
# Use betadisper to assess homogeneity of group dispersions - it first calculates the average distance of group members to the group centroid in multivariate space (generated by a distance matrix). Then, an ANOVA is done to test if the dispersions (variances) of groups are different.
#Extract abundance matrix from phyloseq object
ARGclusters.for.beta.div.exp <- as(otu_table(ARGcluster.aggl.noblanks.exp), "matrix")
# transform into a data frame
ARG.cluster.dataframe.exp <-as.data.frame(ARGclusters.for.beta.div.exp)
ARG.cluster.dataframe.exp

# add copd status to df 
ARG.cluster.dataframe.exp$copdcaco <- ARGcluster.aggl.noblanks@sam_data$copdcaco

BC.distance.exp <- vegdist(ARG.cluster.dataframe.exp, method =  "bray")
# All variables have already been split into quantiles or halves

# Dispersion modelled endotoxin
# Betadisper
# Add columns of the exposure proxies to the dataframe
ARG.cluster.dataframe.exp$MinDistAnyFarm.NEG <- ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.NEG
ARG.cluster.dataframe.exp$MinDistAnyFarm.INV <- ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.INV
ARG.cluster.dataframe.exp$AllFarm.3000m <- ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.3000m
ARG.cluster.dataframe.exp$AllFarm.1000m <- ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.1000m
ARG.cluster.dataframe.exp$AllFarm.500m <- ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.500m
ARG.cluster.dataframe.exp$AllFarm.250m <- ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.250m
ARG.cluster.dataframe.exp$npigsWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.1000m.sum
ARG.cluster.dataframe.exp$npoultryWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.1000m.sum
ARG.cluster.dataframe.exp$ncowsWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.1000m.sum
ARG.cluster.dataframe.exp$nhorsesWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.1000m.sum
ARG.cluster.dataframe.exp$ngoatsWghtDist.1000m.sum<- ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum
ARG.cluster.dataframe.exp$nsheepWghtDist.1000m.sum<- ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.1000m.sum
ARG.cluster.dataframe.exp$nfuranimsWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nfuranimsWghtDist.1000m.sum
ARG.cluster.dataframe.exp$npigsWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.3000m.sum
ARG.cluster.dataframe.exp$npoultryWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.3000m.sum
ARG.cluster.dataframe.exp$ncowsWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.3000m.sum
ARG.cluster.dataframe.exp$nhorsesWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.3000m.sum
ARG.cluster.dataframe.exp$ngoatsWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.3000m.sum
ARG.cluster.dataframe.exp$nsheepWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.3000m.sum
ARG.cluster.dataframe.exp$nfuranimsWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nfuranimsWghtDist.3000m.sum
ARG.cluster.dataframe.exp$nAnyFarmWghtDist.1000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.1000m.sum
ARG.cluster.dataframe.exp$nAnyFarmWghtDist.3000m.sum <- ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.3000m.sum
ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5 <- ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_EUinPM10_AnnualAv_WP99.5
ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5 <- ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_PM10CONC_AnnualAv_WP99.5

head(ARG.cluster.dataframe.exp) # check these have been added - yes!

#DISP_EUinPM10_AnnualAv_WP99.5
Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5 <- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5)
Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5
# Perform an anova using the group dispersions.
anova(Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous ("Null hypothesis of no difference in dispersion between the quartiles")
plot(Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5, permutations = 999)
# we see that the groups do not have significantly different compositions (p>0.05). 
# We can conclude that our groups (quartiles of endotoxin exposure (dispersion modelled)) present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions.

## DISP_PM10CONC_AnnualAv_WP99.5
# Betadisper
Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5 <- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5)
Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5
# Perform an anova using the group dispersions.
anova(Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous("Null hypothesis of no difference in dispersion between the quartiles")
plot(Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5, permutations = 999)
# we see that the 4 groups do not have significantly different compositions (p>0.05). 
# We can conclude that our groups (quartiles of PM10 exposure (dispersion modelled)) present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions.

# Running betadisper on all exposure proxies 
Betadisper.ARGcluster.exp.MinDistAnyFarm.NEG<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$MinDistAnyFarm.NEG)
Betadisper.ARGcluster.exp.MinDistAnyFarm.INV<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$MinDistAnyFarm.INV)
Betadisper.ARGcluster.exp.AllFarm.3000m<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$AllFarm.3000m)
Betadisper.ARGcluster.exp.AllFarm.1000m<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$AllFarm.1000m)
Betadisper.ARGcluster.exp.AllFarm.500m<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$AllFarm.500m)
Betadisper.ARGcluster.exp.AllFarm.250m<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$AllFarm.250m)
Betadisper.ARGcluster.exp.npigsWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$npigsWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.npoultryWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$npoultryWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.ncowsWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$ncowsWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.nhorsesWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nhorsesWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.ngoatsWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$ngoatsWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.nsheepWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nsheepWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.nfuranimsWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nfuranimsWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.npigsWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$npigsWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.npoultryWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$npoultryWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.ncowsWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$ncowsWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.nhorsesWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nhorsesWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.ngoatsWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$ngoatsWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.nsheepWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nsheepWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.nfuranimsWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nfuranimsWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.nAnyFarmWghtDist.1000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nAnyFarmWghtDist.1000m.sum)
Betadisper.ARGcluster.exp.nAnyFarmWghtDist.3000m.sum<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$nAnyFarmWghtDist.3000m.sum)
Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5)
Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5<- betadisper(BC.distance.exp, ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5)

anova(Betadisper.ARGcluster.exp.MinDistAnyFarm.NEG)
anova(Betadisper.ARGcluster.exp.MinDistAnyFarm.INV)
anova(Betadisper.ARGcluster.exp.AllFarm.3000m)
anova(Betadisper.ARGcluster.exp.AllFarm.1000m)
anova(Betadisper.ARGcluster.exp.AllFarm.500m)
anova(Betadisper.ARGcluster.exp.AllFarm.250m)
anova(Betadisper.ARGcluster.exp.npigsWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.npoultryWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.ncowsWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.nhorsesWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.ngoatsWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.nsheepWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.nfuranimsWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.npigsWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.npoultryWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.ncowsWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.nhorsesWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.ngoatsWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.nsheepWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.nfuranimsWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.nAnyFarmWghtDist.1000m.sum)
anova(Betadisper.ARGcluster.exp.nAnyFarmWghtDist.3000m.sum)
anova(Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5)
anova(Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5)

plot(Betadisper.ARGcluster.exp.MinDistAnyFarm.NEG)
plot(Betadisper.ARGcluster.exp.MinDistAnyFarm.INV)
plot(Betadisper.ARGcluster.exp.AllFarm.3000m)
plot(Betadisper.ARGcluster.exp.AllFarm.1000m)
plot(Betadisper.ARGcluster.exp.AllFarm.500m)
plot(Betadisper.ARGcluster.exp.AllFarm.250m)
plot(Betadisper.ARGcluster.exp.npigsWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.npoultryWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.ncowsWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.nhorsesWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.ngoatsWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.nsheepWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.nfuranimsWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.npigsWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.npoultryWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.ncowsWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.nhorsesWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.ngoatsWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.nsheepWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.nfuranimsWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.nAnyFarmWghtDist.1000m.sum)
plot(Betadisper.ARGcluster.exp.nAnyFarmWghtDist.3000m.sum)
plot(Betadisper.ARGcluster.exp.DISP_EUinPM10_AnnualAv_WP99.5)
plot(Betadisper.ARGcluster.exp.DISP_PM10CONC_AnnualAv_WP99.5)

# Running adonis2() function on all exposure proxy variables
# set.seed as adonis() does a permutation test by selecting permutations at random
names(ARG.cluster.dataframe.exp)
set.seed(123)
adonis.MinDistAnyFarm.NEG <- adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$MinDistAnyFarm.NEG, permutations = 999)
set.seed(123)
adonis.MinDistAnyFarm.INV <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$MinDistAnyFarm.INV, permutations = 999)
set.seed(123)
adonis.AllFarm.3000m <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$AllFarm.3000m, permutations = 999)
set.seed(123)
adonis.AllFarm.1000m <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$AllFarm.1000m, permutations = 999)
set.seed(123)
adonis.AllFarm.500m <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$AllFarm.500m, permutations = 999)
set.seed(123)
adonis.AllFarm.250m <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$AllFarm.250m, permutations = 999)
set.seed(123)
adonis.npigsWghtDist.1000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$npigsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.npoultryWghtDist.1000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$npoultryWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.ncowsWghtDist.1000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$ncowsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nhorsesWghtDist.1000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nhorsesWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.ngoatsWghtDist.1000m.sum<-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$ngoatsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nsheepWghtDist.1000m.sum<-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nsheepWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.npigsWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$npigsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.npoultryWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$npoultryWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.ncowsWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$ncowsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nhorsesWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nhorsesWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.ngoatsWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$ngoatsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nsheepWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nsheepWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nAnyFarmWghtDist.1000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nAnyFarmWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nAnyFarmWghtDist.3000m.sum <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$nAnyFarmWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.DISP_EUinPM10_AnnualAv_WP99.5 <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5, permutations = 999)
set.seed(123)
adonis.DISP_PM10CONC_AnnualAv_WP99.5 <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5, permutations = 999)
# None come out as significant.
#print the p-values of each 
adonis.MinDistAnyFarm.NEG$`Pr(>F)`
adonis.MinDistAnyFarm.INV$`Pr(>F)`
adonis.AllFarm.3000m$`Pr(>F)`
adonis.AllFarm.1000m$`Pr(>F)`
adonis.AllFarm.500m $`Pr(>F)`
adonis.AllFarm.250m$`Pr(>F)`
adonis.npigsWghtDist.1000m.sum$`Pr(>F)`
adonis.npoultryWghtDist.1000m.sum$`Pr(>F)` 
adonis.ncowsWghtDist.1000m.sum$`Pr(>F)` 
adonis.nhorsesWghtDist.1000m.sum$`Pr(>F)`
adonis.ngoatsWghtDist.1000m.sum$`Pr(>F)`
adonis.nsheepWghtDist.1000m.sum$`Pr(>F)`
adonis.npigsWghtDist.3000m.sum$`Pr(>F)`
adonis.npoultryWghtDist.3000m.sum$`Pr(>F)` 
adonis.ncowsWghtDist.3000m.sum$`Pr(>F)` 
adonis.nhorsesWghtDist.3000m.sum$`Pr(>F)`
adonis.ngoatsWghtDist.3000m.sum$`Pr(>F)` 
adonis.nsheepWghtDist.3000m.sum$`Pr(>F)`
adonis.nAnyFarmWghtDist.1000m.sum$`Pr(>F)`
adonis.nAnyFarmWghtDist.3000m.sum$`Pr(>F)` 
adonis.DISP_EUinPM10_AnnualAv_WP99.5$`Pr(>F)`
adonis.DISP_PM10CONC_AnnualAv_WP99.5$`Pr(>F)` 

# Print the R^2 of each exposure proxy - see the first column for the R2 of the exposure proxy 
adonis.MinDistAnyFarm.NEG$R2
adonis.MinDistAnyFarm.INV$R2
adonis.AllFarm.3000m$R2
adonis.AllFarm.1000m$R2
adonis.AllFarm.500m $R2
adonis.AllFarm.250m$R2
adonis.npigsWghtDist.1000m.sum$R2
adonis.npoultryWghtDist.1000m.sum$R2 
adonis.ncowsWghtDist.1000m.sum$R2 
adonis.nhorsesWghtDist.1000m.sum$R2
adonis.ngoatsWghtDist.1000m.sum$R2
adonis.nsheepWghtDist.1000m.sum$R2
adonis.npigsWghtDist.3000m.sum$R2
adonis.npoultryWghtDist.3000m.sum$R2 
adonis.ncowsWghtDist.3000m.sum$R2 
adonis.nhorsesWghtDist.3000m.sum$R2
adonis.ngoatsWghtDist.3000m.sum$R2 
adonis.nsheepWghtDist.3000m.sum$R2
adonis.nAnyFarmWghtDist.1000m.sum$R2
adonis.nAnyFarmWghtDist.3000m.sum$R2 
adonis.DISP_EUinPM10_AnnualAv_WP99.5$R2
adonis.DISP_PM10CONC_AnnualAv_WP99.5$R2
# 2 variables came out as nearly significant: DISP_EUinPM10_AnnualAv_WP99.5 (p=0.078) & nhorsesWghtDist.3000m.sum (p=0.083) 


# Re-run adonis2 with COPD status in the formula - as a covariate  - TBC
# Maybe I need to add copd status to the PERMANOVA to adjust for differences?
ARG.cluster.dataframe.exp$copdcaco <- ARGcluster.aggl.noblanks.LUR@sam_data$copdcaco # add copd status into the dataframe
set.seed(123)
adonis.MinDistAnyFarm.NEG.copd <- adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$copdcaco + ARG.cluster.dataframe.exp$MinDistAnyFarm.NEG, permutations = 999)

adonis.MinDistAnyFarm.INV.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$MinDistAnyFarm.INV, permutations = 999)
set.seed(123)
adonis.AllFarm.3000m.copd <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$copdcaco + ARG.cluster.dataframe.exp$AllFarm.3000m, permutations = 999)
set.seed(123)
adonis.AllFarm.1000m.copd <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$copdcaco + ARG.cluster.dataframe.exp$AllFarm.1000m, permutations = 999)
set.seed(123)
adonis.AllFarm.500m.copd <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$copdcaco + ARG.cluster.dataframe.exp$AllFarm.500m, permutations = 999)
set.seed(123)
adonis.AllFarm.250m.copd <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$AllFarm.250m, permutations = 999)
set.seed(123)
adonis.npigsWghtDist.1000m.sum.copd <-adonis2(BC.distance.exp~ ARG.cluster.dataframe.exp$copdcaco + ARG.cluster.dataframe.exp$npigsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.npoultryWghtDist.1000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$npoultryWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.ncowsWghtDist.1000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$ncowsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nhorsesWghtDist.1000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nhorsesWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.ngoatsWghtDist.1000m.sum.copd<-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$ngoatsWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nsheepWghtDist.1000m.sum.copd<-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nsheepWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.npigsWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$npigsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.npoultryWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$npoultryWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.ncowsWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$ncowsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nhorsesWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nhorsesWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.ngoatsWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$ngoatsWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nsheepWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nsheepWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.nAnyFarmWghtDist.1000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nAnyFarmWghtDist.1000m.sum, permutations = 999)
set.seed(123)
adonis.nAnyFarmWghtDist.3000m.sum.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$nAnyFarmWghtDist.3000m.sum, permutations = 999)
set.seed(123)
adonis.DISP_EUinPM10_AnnualAv_WP99.5.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$DISP_EUinPM10_AnnualAv_WP99.5, permutations = 999)
set.seed(123)
adonis.DISP_PM10CONC_AnnualAv_WP99.5.copd <-adonis2(BC.distance.exp~ARG.cluster.dataframe.exp$copdcaco +  ARG.cluster.dataframe.exp$DISP_PM10CONC_AnnualAv_WP99.5, permutations = 999)

# None come out as significant.
#print the p-values of each 
adonis.MinDistAnyFarm.NEG.copd$`Pr(>F)`
adonis.MinDistAnyFarm.INV.copd$`Pr(>F)`
adonis.AllFarm.3000m.copd$`Pr(>F)`
adonis.AllFarm.1000m.copd$`Pr(>F)`
adonis.AllFarm.500m.copd $`Pr(>F)`
adonis.AllFarm.250m.copd$`Pr(>F)`
adonis.npigsWghtDist.1000m.sum.copd$`Pr(>F)`
adonis.npoultryWghtDist.1000m.sum.copd$`Pr(>F)` 
adonis.ncowsWghtDist.1000m.sum.copd$`Pr(>F)` 
adonis.nhorsesWghtDist.1000m.sum.copd$`Pr(>F)`
adonis.ngoatsWghtDist.1000m.sum.copd$`Pr(>F)`
adonis.nsheepWghtDist.1000m.sum.copd$`Pr(>F)`
adonis.npigsWghtDist.3000m.sum.copd$`Pr(>F)`
adonis.npoultryWghtDist.3000m.sum.copd$`Pr(>F)` 
adonis.ncowsWghtDist.3000m.sum.copd$`Pr(>F)` 
adonis.nhorsesWghtDist.3000m.sum.copd$`Pr(>F)`
adonis.ngoatsWghtDist.3000m.sum.copd$`Pr(>F)` 
adonis.nsheepWghtDist.3000m.sum.copd$`Pr(>F)`
adonis.nAnyFarmWghtDist.1000m.sum.copd$`Pr(>F)`
adonis.nAnyFarmWghtDist.3000m.sum.copd$`Pr(>F)` 
adonis.DISP_EUinPM10_AnnualAv_WP99.5.copd$`Pr(>F)`
adonis.DISP_PM10CONC_AnnualAv_WP99.5.copd$`Pr(>F)` 

# Now all p-values are adjusted for copd status and none come out as significantly associated with beta diversity

# Print the R^2 of each exposure proxy - see the first column for the R2 of the exposure proxy 

adonis.MinDistAnyFarm.NEG.copd$R2
adonis.MinDistAnyFarm.INV.copd$R2
adonis.AllFarm.3000m.copd$R2
adonis.AllFarm.1000m.copd$R2
adonis.AllFarm.500m.copd $R2
adonis.AllFarm.250m.copd$R2
adonis.npigsWghtDist.1000m.sum.copd$R2
adonis.npoultryWghtDist.1000m.sum.copd$R2 
adonis.ncowsWghtDist.1000m.sum.copd$R2 
adonis.nhorsesWghtDist.1000m.sum.copd$R2
adonis.ngoatsWghtDist.1000m.sum.copd$R2
adonis.nsheepWghtDist.1000m.sum.copd$R2
adonis.npigsWghtDist.3000m.sum.copd$R2
adonis.npoultryWghtDist.3000m.sum.copd$R2 
adonis.ncowsWghtDist.3000m.sum.copd$R2 
adonis.nhorsesWghtDist.3000m.sum.copd$R2
adonis.ngoatsWghtDist.3000m.sum.copd$R2 
adonis.nsheepWghtDist.3000m.sum.copd$R2
adonis.nAnyFarmWghtDist.1000m.sum.copd$R2
adonis.nAnyFarmWghtDist.3000m.sum.copd$R2 
adonis.DISP_EUinPM10_AnnualAv_WP99.5.copd$R2
adonis.DISP_PM10CONC_AnnualAv_WP99.5.copd$R2 

```
## PCoA ordinations
```{r}
# PCoA 
# I will construct principal coordinates analysis based on Bray-Curtis dissimilarities. These measures are based on abundance or read count data. It generates differences in ARG abundances between two samples (e.g., at species level) which are from 0 to 1 (where 0= both samples share the same species at exactly the same abundances and 1= both samples have complete different species abundances).
ARGcluster.aggl.noblanks.exp <- ARGcluster.aggl.noblanks
sample_data(ARGcluster.aggl.noblanks.exp)
sam.data.new <- as.data.frame(sample_data(livestock.exp.df.noblanks.df))
sample_data(ARGcluster.aggl.noblanks.exp) <- sam.data.new
names(ARGcluster.aggl.noblanks.exp@sam_data)

# Firstly I need to categorise my exposure proxy variables which are currently continuous numeric to quantiles (factor variables) (as WvK did for his analysis too)- I want an equal % of variables in each quantile
# I start with the livestock proxies which came out significant in the alpha diversity linear models 
ARGcluster.aggl.noblanks.exp.quant <- ARGcluster.aggl.noblanks.exp
# I will use the quantcut() function in gtools -quantcut(x, q = 4, na.rm = TRUE, ...)

ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.NEG<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.NEG, q=4, labels =c("1st quantile (minDistAnyFarm.NEG)", "2nd quantile (minDistAnyFarm.NEG)", "3rd quantile (minDistAnyFarm.NEG)", "4th quantile (minDistAnyFarm.NEG)"))
# MinDistAnyFarm.INV
ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.INV <- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.INV, q=4, labels =c("1st quantile (MinDistAnyFarm.INV)", "2nd quantile (MinDistAnyFarm.INV)", "3rd quantile (MinDistAnyFarm.INV)", "4th quantile (MinDistAnyFarm.INV)"))
# AllFarm.3000m
ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.3000m<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.3000m, q=4, labels =c("1st quantile (AllFarm.3000m)", "2nd quantile (AllFarm.3000m)", "3rd quantile (AllFarm.3000m)", "4th quantile (AllFarm.3000m)"))
#AllFarm.1000m
ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.1000m<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.1000m, q=4, labels =c("1st quantile (AllFarm.1000m)", "2nd quantile (AllFarm.1000m)", "3rd quantile (AllFarm.1000m)", "4th quantile (AllFarm.1000m)"))
#AllFarm.500m - unable to split into quantiles due to lots of zeros - I have split in half instead
ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.500m<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.500m, q=2,labels =c("Bottom half (AllFarm.500m)", "Top half (AllFarm.500m)"))
# #AllFarm.250m  -  difficult to split as the majority are equal to zero…I could split into 0 vs not 0 maybe? Is this that explanatory though?
# ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.250m<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.250m, q=2)
#npigsWghtDist.1000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.1000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.1000m.sum, q=2, labels=c("Bottom half (npigsWghtDist.1000m.sum)", "Top half (npigsWghtDist.1000m.sum)"))
#npoultryWghtDist.1000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.1000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.1000m.sum, q=2, labels=c("Bottom half (npoultryWghtDist.1000m.sum)", "Top half (npoultryWghtDist.1000m.sum)"))
#ncowsWghtDist.1000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.1000m.sum<- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.1000m.sum, q=4, labels =c("1st quantile (ncowsWghtDist.1000m.sum)", "2nd quantile (ncowsWghtDist.1000m.sum)", "3rd quantile (ncowsWghtDist.1000m.sum)", "4th quantile (ncowsWghtDist.1000m.sum)"))
#ngoatsWghtDist.1000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum <- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum, q=2, labels=c("Bottom half (ngoatsWghtDist.1000m.sum)", "Top half (ngoatsWghtDist.1000m.sum)")) # unable to split ngoatsWghtDist.1000m.sum into half
#nhorsesWghtDist.1000m.sum 
ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.1000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.1000m.sum, q=4, labels =c("1st quantile (nhorsesWghtDist.1000m.sum)", "2nd quantile (nhorsesWghtDist.1000m.sum)", "3rd quantile (nhorsesWghtDist.1000m.sum)", "4th quantile (nhorsesWghtDist.1000m.sum)"))
# ngoatsWghtDist.1000m.sum
# Difficult to split as the majority are equal to zero…I could split into 0 vs not 0 maybe?
ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum <- ifelse(ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum == 0, "No goat farms in 1000m","1 or more goat farms within 1000m")
# Split nsheepWghtDist.1000m.sum into quantiles
# It is not possible to split this variable into quantiles (because more than one quantile obtains the same value - as there are so many zero values), therefore instead I can split into 2 - bottom and top halves
ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.1000m.sum <- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.1000m.sum, q=2, labels =c("bottom half", "top half"))
# npigsWghtDist.3000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.3000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$npigsWghtDist.3000m.sum, q=2, labels =c("Bottom half (npigsWghtDist.3000m.sum)", "Top half (npigsWghtDist.3000m.sum)"))
#npoultryWghtDist.3000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.3000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$npoultryWghtDist.3000m.sum, q=4, labels =c("1st quantile (npoultryWghtDist.3000m.sum)", "2nd quantile (npoultryWghtDist.3000m.sum)", "3rd quantile (npoultryWghtDist.3000m.sum)", "4th quantile (npoultryWghtDist.3000m.sum)"))
#ncowsWghtDist.3000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.3000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$ncowsWghtDist.3000m.sum, q=4, labels =c("1st quantile (ncowsWghtDist.3000m.sum)", "2nd quantile (ncowsWghtDist.3000m.sum)", "3rd quantile (ncowsWghtDist.3000m.sum)", "4th quantile (ncowsWghtDist.3000m.sum)"))
# Split nhorsesWghtDist.3000m.sum into quantiles
ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.3000m.sum <- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nhorsesWghtDist.3000m.sum, q=4, labels =c("1st quantile (nhorsesWghtDist.3000m.sum)", "2nd quantile (nhorsesWghtDist.3000m.sum)", "3rd quantile (nhorsesWghtDist.3000m.sum)", "4th quantile(nhorsesWghtDist.3000m.sum)"))
# Split ngoatsWghtDist.3000m.sum into quantiles
ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.3000m.sum <- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.3000m.sum, q=4, labels =c("1st quantile (ngoatsWghtDist.3000m.sum)", "2nd quantile (ngoatsWghtDist.3000m.sum)", "3rd quantile (ngoatsWghtDist.3000m.sum)", "4th quantile(ngoatsWghtDist.3000m.sum)"))
#nsheepWghtDist.3000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.3000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.3000m.sum, q=4, labels =c("1st quantile (nsheepWghtDist.3000m.sum)", "2nd quantile (nsheepWghtDist.3000m.sum)", "3rd quantile (nsheepWghtDist.3000m.sum)", "4th quantile (nsheepWghtDist.3000m.sum)"))
#nAnyFarmWghtDist.1000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.1000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.1000m.sum, q=4, labels =c("1st quantile (nAnyFarmWghtDist.1000m.sum)", "2nd quantile (nAnyFarmWghtDist.1000m.sum)", "3rd quantile (nAnyFarmWghtDist.1000m.sum)", "4th quantile (nAnyFarmWghtDist.1000m.sum)"))
#nAnyFarmWghtDist.3000m.sum
ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.3000m.sum<-quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$nAnyFarmWghtDist.3000m.sum, q=4, labels =c("1st quantile (nAnyFarmWghtDist.3000m.sum)", "2nd quantile (nAnyFarmWghtDist.3000m.sum)", "3rd quantile (nAnyFarmWghtDist.3000m.sum)", "4th  quantile (nAnyFarmWghtDist.3000m.sum) "))
# DISP_EUinPM10_AnnualAv_WP99.5  
ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_EUinPM10_AnnualAv_WP99.5<- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_EUinPM10_AnnualAv_WP99.5, q=4, labels =c("1st quantile (DISP_EUinPM10_AnnualAv_WP99.5)", "2nd quantile (DISP_EUinPM10_AnnualAv_WP99.5)", "3rd quantile (DISP_EUinPM10_AnnualAv_WP99.5)", "4th quantile (DISP_EUinPM10_AnnualAv_WP99.5)"))
# DISP_PM10CONC_AnnualAv_WP99.5 
ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_PM10CONC_AnnualAv_WP99.5<- quantcut(ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_PM10CONC_AnnualAv_WP99.5, q=4, labels =c("1st quantile (DISP_PM10CONC_AnnualAv_WP99.5)", "2nd quantile (DISP_PM10CONC_AnnualAv_WP99.5)", "3rd quantile (DISP_PM10CONC_AnnualAv_WP99.5)", "4th quantile (DISP_PM10CONC_AnnualAv_WP99.5)"))


# Check a few variabes to ensure quantile/half splitting has been successful

# check the quantile splitting of these other exposure proxies has been successful
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.NEG)
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$MinDistAnyFarm.INV)
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.3000m)
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.1000m)
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$AllFarm.500m)
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.1000m.sum) # should be in half
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$nsheepWghtDist.1000m.sum)# should be in half
barchart(ARGcluster.aggl.noblanks.exp.quant@sam_data$DISP_EUinPM10_AnnualAv_WP99.5)
# Yes it appears that splitting of the exposure proxy variables has all been performed correctly 

# PCoA on the BC dissimilarity matrix of the clustered resistome data (as before)
ARGcluster.aggl.PCoA.exp.quant <- ordinate(ARGcluster.aggl.noblanks.exp.quant, method="PCoA", distance="bray")

# Extract the vectors from the PCoA 
ARGcluster.aggl.PCoA.exp.quant$vectors # i.e. this tells us how much of the total variance is explained by each of the axes with respect to the total variance

# Show dominant eigen planes
plot_scree(ARGcluster.aggl.PCoA.exp.quant)

# Exploring all exposure variables in PCoAs 
# MinDistAnyFarm.NEG
ARGcluster.aggl.PCoA.exp.plot.MinDistAnyFarm.NEG.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="MinDistAnyFarm.NEG", shape="MinDistAnyFarm.NEG" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by MinDistAnyFarm.NEG quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.MinDistAnyFarm.NEG.quant

# MinDistAnyFarm.INV
ARGcluster.aggl.PCoA.exp.plot.MinDistAnyFarm.INV.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="MinDistAnyFarm.INV", shape="MinDistAnyFarm.INV" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by MinDistAnyFarm.INV quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.MinDistAnyFarm.INV.quant

# AllFarm.3000m
ARGcluster.aggl.PCoA.exp.plot.Allfarm.3000m <- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="AllFarm.3000m", shape="AllFarm.3000m" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by AllFarm.3000m quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.Allfarm.3000m

# AllFarm.1000m
ARGcluster.aggl.PCoA.exp.plot.Allfarm.1000m.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="AllFarm.1000m", shape="AllFarm.1000m" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by AllFarm.1000m quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.Allfarm.1000m.quant

#AllFarm.500m
ARGcluster.aggl.PCoA.exp.plot.Allfarm.500m <- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="AllFarm.500m", shape="AllFarm.500m" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by AllFarm.500m halves") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.Allfarm.500m

#npigsWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.npigsWghtDist.1000m.sum.half<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="npigsWghtDist.1000m.sum", shape="npigsWghtDist.1000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by npigsWghtDist.1000m.sum halves") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.npigsWghtDist.1000m.sum.half

# npoultryWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.npoultryWghtDist.1000m.sum.half<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="npoultryWghtDist.1000m.sum", shape="npoultryWghtDist.1000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by npoultryWghtDist.1000m.sum halves") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.npoultryWghtDist.1000m.sum.half

#ncowsWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.ncowsWghtDist.1000m.sum<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="ncowsWghtDist.1000m.sum", shape="ncowsWghtDist.1000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by ncowsWghtDist.1000m.sum quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.ncowsWghtDist.1000m.sum

#nhorsesWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.1000m.sum.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "nhorsesWghtDist.1000m.sum", shape="nhorsesWghtDist.1000m.sum") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by nhorsesWghtDist.1000m.sum quantiles") +
  labs(legend="nhorsesWghtDist.1000m.sum exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = nhorsesWghtDist.1000m.sum))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.1000m.sum.quant
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.1000m.sum.quant + stat_ellipse()

# ngoatsWghtDist.1000m.sum.quant
ARGcluster.aggl.PCoA.exp.plot.ngoatsWghtDist.1000m.sum.quant <- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="ngoatsWghtDist.1000m.sum", shape="ngoatsWghtDist.1000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by quantiles of ngoatsWghtDist.1000m.sum") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() +
  theme(plot.title = element_text(size = 20, face = "bold"), legend.title=element_text(size=20), legend.text=element_text(size=15))
ARGcluster.aggl.PCoA.exp.plot.ngoatsWghtDist.1000m.sum.quant

# nsheepWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.nsheepWghtDist.1000m.sum.half <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "nsheepWghtDist.1000m.sum", shape="nsheepWghtDist.1000m.sum") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by nsheepWghtDist.1000m.sum quantiles") +
  labs(legend="nsheepWghtDist.1000m.sum exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = nsheepWghtDist.1000m.sum))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.nsheepWghtDist.1000m.sum.half
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.nsheepWghtDist.1000m.sum.half + stat_ellipse()



#npigsWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.npigsWghtDist.3000m.sum.half<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="npigsWghtDist.3000m.sum", shape="npigsWghtDist.3000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by npigsWghtDist.3000m.sum halves") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.npigsWghtDist.3000m.sum.half

#npoultryWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.npoultryWghtDist.3000m.sum<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="npoultryWghtDist.3000m.sum", shape="npoultryWghtDist.3000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by npoultryWghtDist.3000m.sum quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.npoultryWghtDist.3000m.sum

#ncowsWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.ncowsWghtDist.3000m.sum.quant<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="ncowsWghtDist.3000m.sum", shape="ncowsWghtDist.3000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by ncowsWghtDist.3000m.sum quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.ncowsWghtDist.3000m.sum.quant

#nhorsesWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.3000m.sum.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "nhorsesWghtDist.3000m.sum", shape="nhorsesWghtDist.3000m.sum") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by nhorsesWghtDist.3000m.sum quantiles") +
  labs(legend="nhorsesWghtDist.3000m.sum exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = nhorsesWghtDist.3000m.sum))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.3000m.sum.quant
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.nhorsesWghtDist.3000m.sum.quant + stat_ellipse()

#ngoatsWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.ngoatsWghtDist.3000m.sum.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "ngoatsWghtDist.3000m.sum", shape="ngoatsWghtDist.3000m.sum") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by ngoatsWghtDist.3000m.sum quantiles") +
  labs(legend="ngoatsWghtDist.3000m.sum exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = ngoatsWghtDist.3000m.sum))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.ngoatsWghtDist.3000m.sum.quant
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.ngoatsWghtDist.3000m.sum.quant + stat_ellipse()

#nsheepWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.nsheepWghtDist.3000m.sum.quant<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="nsheepWghtDist.3000m.sum", shape="nsheepWghtDist.3000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by nsheepWghtDist.3000m.sum quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.nsheepWghtDist.3000m.sum.quant

#nAnyFarmWghtDist.1000m.sum
ARGcluster.aggl.PCoA.exp.plot.nAnyFarmWghtDist.1000m.sum<- plot_ordination(ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color="nAnyFarmWghtDist.1000m.sum", shape="nAnyFarmWghtDist.1000m.sum" ) +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - coloured by nAnyFarmWghtDist.1000m.sum quantiles") +
    geom_point(size = 3) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp@sam_data),hjust=-0.3, vjust=-0.5 ) )+ stat_ellipse() 
ARGcluster.aggl.PCoA.exp.plot.nAnyFarmWghtDist.1000m.sum

# nAnyFarmWghtDist.3000m.sum
ARGcluster.aggl.PCoA.exp.plot.nAnyFarmWghtDist.3000m.sum <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "nAnyFarmWghtDist.3000m.sum", shape="nAnyFarmWghtDist.3000m.sum") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by nAnyFarmWghtDist.3000m.sum quantiles") +
  labs(legend="nAnyFarmWghtDist.3000m.sum exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = nAnyFarmWghtDist.3000m.sum))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.nAnyFarmWghtDist.3000m.sum
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.nAnyFarmWghtDist.3000m.sum + stat_ellipse()

# Ordination on dispersion modelled endotoxin concentration DISP_EUinPM10_AnnualAv_WP99.5 quantiles 
ARGcluster.aggl.PCoA.exp.plot.DISP.endotoxin.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "DISP_EUinPM10_AnnualAv_WP99.5", shape="DISP_EUinPM10_AnnualAv_WP99.5") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by endotoxin exposure quantiles") +
  labs(legend="Endotoxin exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = DISP_EUinPM10_AnnualAv_WP99.5))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.DISP.endotoxin.quant
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.DISP.endotoxin.quant + stat_ellipse()

# Ordination on dispersion modelled PM10 concentration quantiles (DISP_PM10CONC_AnnualAv_WP99.5)
ARGcluster.aggl.PCoA.exp.plot.DISPPM10.quant <- plot_ordination( ARGcluster.aggl.noblanks.exp.quant, ARGcluster.aggl.PCoA.exp.quant, color = "DISP_PM10CONC_AnnualAv_WP99.5", shape="DISP_PM10CONC_AnnualAv_WP99.5") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by PM10 exposure quantiles") +
  labs(legend="PM10 exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.quant@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = DISP_PM10CONC_AnnualAv_WP99.5))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.DISPPM10.quant
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.DISPPM10.quant + stat_ellipse()

# For all of the ordinations it appears that there are no associations - i.e. lots of overlap of all ordinations

# Now I will try an alternative splitting of the variables
# Try splitting endotoxin exposure into high and low concentrations instead 
# Split DISP_EUinPM10_AnnualAv_WP99.5 into high and low 
ARGcluster.aggl.noblanks.exp.half <- ARGcluster.aggl.noblanks
sample_data(ARGcluster.aggl.noblanks.exp.half)
sam.data.new <- as.data.frame(sample_data(livestock.exp.df.noblanks.df))
sample_data(ARGcluster.aggl.noblanks.exp.half) <- sam.data.new
ARGcluster.aggl.noblanks.exp.half@sam_data$DISP_EUinPM10_AnnualAv_WP99.5<- quantcut(ARGcluster.aggl.noblanks.exp.half@sam_data$DISP_EUinPM10_AnnualAv_WP99.5, q=2, labels =c("Low exposure (DISP_EUinPM10_AnnualAv_WP99.5)", "High exposure (DISP_EUinPM10_AnnualAv_WP99.5)"))

# Run the ordination on this DISP_EUinPM10_AnnualAv_WP99.5 
ARGcluster.aggl.PCoA.exp.plot.DISP.ENDO.half <- plot_ordination( ARGcluster.aggl.noblanks.exp.half, ARGcluster.aggl.PCoA.exp.half, color = "DISP_EUinPM10_AnnualAv_WP99.5", shape="DISP_EUinPM10_AnnualAv_WP99.5") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by endotoxin exposure quantiles") +
  labs(legend="Endotoxin exposure (high vs.low)")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.half@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = DISP_EUinPM10_AnnualAv_WP99.5))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.DISP.ENDO.half
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.DISP.ENDO.half + stat_ellipse()

# Try splitting PM10 exposure into high and low concentrations instead
ARGcluster.aggl.noblanks.exp.half@sam_data$DISP_PM10CONC_AnnualAv_WP99.5<- quantcut(ARGcluster.aggl.noblanks.exp.half@sam_data$DISP_PM10CONC_AnnualAv_WP99.5, breaks=2, labels =c("Low exposure (DISP_PM10CONC_AnnualAv_WP99.5)", "High exposure (DISP_PM10CONC_AnnualAv_WP99.5)"))

ARGcluster.aggl.PCoA.exp.plot.DISPPM10.half <- plot_ordination( ARGcluster.aggl.noblanks.exp.half, ARGcluster.aggl.PCoA.exp.half, color = "DISP_PM10CONC_AnnualAv_WP99.5", shape="DISP_PM10CONC_AnnualAv_WP99.5") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, \n90% identity clustered) - coloured by PM10 exposure quantiles") +
  labs(legend="PM10 exposure (high vs.low)")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.exp.half@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 15))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = DISP_PM10CONC_AnnualAv_WP99.5))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
ARGcluster.aggl.PCoA.exp.plot.DISPPM10.half
# Add ellipses 
ARGcluster.aggl.PCoA.exp.plot.DISPPM10.half + stat_ellipse()

# No clear clustering even when dispersion modelled PM10 or endotoxin are just stratified into halves (high and low exposure)...no effect of dispersion modelled PM10 or endotoxin on resistome composition. 
```
# LUR and RF-modelled livestock exposures
## PERMANOVAs
```{r}
#Extract abundance matrix from phyloseq object
ARGclusters.for.beta.div.LUR.RF.estimates <- as(otu_table(ARGcluster.aggl.noblanks.LUR.RF.estimates), "matrix")

# transform into a data frame
ARG.cluster.LUR.RF.df <- as.data.frame(ARGclusters.for.beta.div.LUR.RF.estimates)
ARG.cluster.LUR.RF.df

# compute BC distances between samples
BC.distance.LUR.RF <- vegdist(ARG.cluster.LUR.RF.df, method =  "bray")

# add columns to the df now
ARG.cluster.LUR.RF.df$E.coli_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_LUR_estimates
ARG.cluster.LUR.RF.df$Staph_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_LUR_estimates
ARG.cluster.LUR.RF.df$tetW_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_LUR_estimates
ARG.cluster.LUR.RF.df$mecA_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_LUR_estimates
ARG.cluster.LUR.RF.df$E.coli_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_RF_predictions
ARG.cluster.LUR.RF.df$Staph_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_RF_predictions
ARG.cluster.LUR.RF.df$tetW_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_RF_predictions
ARG.cluster.LUR.RF.df$mecA_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_RF_predictions

# E.coli_LUR_estimates 
# Betadisper
Betadisper.ARGcluster.E.coli_LUR_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$E.coli_LUR_estimates)
Betadisper.ARGcluster.E.coli_LUR_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.E.coli_LUR_estimates) # p-value = 0.3734 - group dispersions are homogenous
plot(Betadisper.ARGcluster.E.coli_LUR_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$E.coli_LUR_estimates, permutations = 999)# p-value = 0.292 - no significant differences in group centroids-  We can conclude that our groups (quartiles of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# Staph_LUR_estimates
# Betadisper
Betadisper.ARGcluster.Staph_LUR_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$Staph_LUR_estimates)
Betadisper.ARGcluster.Staph_LUR_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.Staph_LUR_estimates) # p-value = 0.8389 - group dispersions are homogenous
plot(Betadisper.ARGcluster.Staph_LUR_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$Staph_LUR_estimates, permutations = 999)# p-value = 0.42 - no significant differences in group centroids-  We can conclude that our groups (quartiles of Staph (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# tetW_LUR_estimates
# Betadisper
Betadisper.ARGcluster.tetW_LUR_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$tetW_LUR_estimates)
Betadisper.ARGcluster.tetW_LUR_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.tetW_LUR_estimates) # p-value = 0.78 - group dispersions are homogenous
plot(Betadisper.ARGcluster.tetW_LUR_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$tetW_LUR_estimates, permutations = 999)# p-value = 0.194 - no significant differences in group centroids-  We can conclude that our groups (quartiles of tetW (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# mecA_LUR_estimates
# Betadisper
Betadisper.ARGcluster.mecA_LUR_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$mecA_LUR_estimates)
Betadisper.ARGcluster.mecA_LUR_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.mecA_LUR_estimates) # p-value = 0.8345 - group dispersions are homogenous
plot(Betadisper.ARGcluster.mecA_LUR_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$mecA_LUR_estimates, permutations = 999)# p-value = 0.305 - no significant differences in group centroids-  We can conclude that our groups (quartiles of mecA (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# E.coli_RF_predictions 
# Betadisper
Betadisper.ARGcluster.E.coli_RF_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$E.coli_RF_predictions)
Betadisper.ARGcluster.E.coli_RF_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.E.coli_RF_estimates) # p-value = 0.5236 - group dispersions are homogenous
plot(Betadisper.ARGcluster.E.coli_RF_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$E.coli_RF_predictions, permutations = 999)# p-value = 0.072  - borderline no significant differences in group centroids-  We can conclude that our groups (quartiles of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# Staph_RF_predictions
# Betadisper
Betadisper.ARGcluster.Staph_RF_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$Staph_RF_predictions)
Betadisper.ARGcluster.Staph_RF_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.Staph_RF_estimates) # p-value = 0.7748 - group dispersions are homogenous
plot(Betadisper.ARGcluster.Staph_RF_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$Staph_RF_predictions, permutations = 999)# p-value = 0.775 - no significant differences in group centroids-  We can conclude that our groups (quartiles of Staph (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# tetW_RF_predictions
# Betadisper
Betadisper.ARGcluster.tetW_RF_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$tetW_RF_predictions)
Betadisper.ARGcluster.tetW_RF_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.tetW_RF_estimates) # p-value = 0.9639 - group dispersions are homogenous
plot(Betadisper.ARGcluster.tetW_RF_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$tetW_RF_predictions, permutations = 999)# p-value = 0.321 - no significant differences in group centroids-  We can conclude that our groups (quartiles of tetW (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# mecA_RF_predictions
# Betadisper
Betadisper.ARGcluster.mecA_RF_estimates <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df$mecA_RF_predictions)
Betadisper.ARGcluster.mecA_RF_estimates
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.mecA_RF_estimates) # p-value = 0.6946 - group dispersions are homogenous
plot(Betadisper.ARGcluster.mecA_RF_estimates) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$mecA_LUR_estimates, permutations = 999)# p-value = 0.291 - no significant differences in group centroids-  We can conclude that our groups (quartiles of mecA (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)


# High vs low exposed
ARGclusters.for.beta.div.LUR.RF.estimates <- as(otu_table(ARGcluster.aggl.noblanks.LUR.RF.estimates), "matrix")
# transform into a data frame
ARG.cluster.LUR.RF.df_HALVES <- as.data.frame(ARGclusters.for.beta.div.LUR.RF.estimates)
ARG.cluster.LUR.RF.df_HALVES

# compute BC distances between samples
BC.distance.LUR.RF <- vegdist(ARG.cluster.LUR.RF.df_HALVES, method =  "bray")

# add columns to the df now
# add columns to the df now
ARG.cluster.LUR.RF.df_HALVES$E.coli_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_LUR_estimates
ARG.cluster.LUR.RF.df_HALVES$Staph_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_LUR_estimates
ARG.cluster.LUR.RF.df_HALVES$tetW_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_LUR_estimates
ARG.cluster.LUR.RF.df_HALVES$mecA_LUR_estimates <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_LUR_estimates
ARG.cluster.LUR.RF.df_HALVES$E.coli_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_RF_predictions
ARG.cluster.LUR.RF.df_HALVES$Staph_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_RF_predictions
ARG.cluster.LUR.RF.df_HALVES$tetW_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_RF_predictions
ARG.cluster.LUR.RF.df_HALVES$mecA_RF_predictions <- ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_RF_predictions

# E.coli_LUR_estimates 
# Betadisper
Betadisper.ARGcluster.E.coli_LUR_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$E.coli_LUR_estimates)
Betadisper.ARGcluster.E.coli_LUR_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.E.coli_LUR_estimates_HALVES) # p-value = 0.3734 - group dispersions are homogenous
plot(Betadisper.ARGcluster.E.coli_LUR_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$E.coli_LUR_estimates, permutations = 999)# p-value = 0.292 - no significant differences in group centroids-  We can conclude that our groups (halves of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# Staph_LUR_estimates
# Betadisper
Betadisper.ARGcluster.Staph_LUR_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$Staph_LUR_estimates)
Betadisper.ARGcluster.Staph_LUR_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.Staph_LUR_estimates_HALVES) # p-value = 0.8389 - group dispersions are homogenous
plot(Betadisper.ARGcluster.Staph_LUR_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$Staph_LUR_estimates, permutations = 999)# p-value = 0.42 - no significant differences in group centroids-  We can conclude that our groups (halves of Staph (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# tetW_LUR_estimates
# Betadisper
Betadisper.ARGcluster.tetW_LUR_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$tetW_LUR_estimates)
Betadisper.ARGcluster.tetW_LUR_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.tetW_LUR_estimates_HALVES) # p-value = 0.78 - group dispersions are homogenous
plot(Betadisper.ARGcluster.tetW_LUR_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$tetW_LUR_estimates, permutations = 999)# p-value = 0.194 - no significant differences in group centroids-  We can conclude that our groups (halves of tetW (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# mecA_LUR_estimates
# Betadisper
Betadisper.ARGcluster.mecA_LUR_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$mecA_LUR_estimates)
Betadisper.ARGcluster.mecA_LUR_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.mecA_LUR_estimates_HALVES) # p-value = 0.8345 - group dispersions are homogenous
plot(Betadisper.ARGcluster.mecA_LUR_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$mecA_LUR_estimates, permutations = 999)# p-value = 0.305 - no significant differences in group centroids-  We can conclude that our groups (halves of mecA (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# E.coli_RF_predictions 
# Betadisper
Betadisper.ARGcluster.E.coli_RF_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$E.coli_RF_predictions)
Betadisper.ARGcluster.E.coli_RF_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.E.coli_RF_estimates_HALVES) # p-value = 0.5738 - group dispersions are homogenous
plot(Betadisper.ARGcluster.E.coli_RF_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$E.coli_RF_predictions, permutations = 999)# p-value = 0.945  - borderline no significant differences in group centroids-  We can conclude that our groups (halves of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# Staph_RF_predictions
# Betadisper
Betadisper.ARGcluster.Staph_RF_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$Staph_RF_predictions)
Betadisper.ARGcluster.Staph_RF_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.Staph_RF_estimates_HALVES) # p-value = 0.4468 - group dispersions are homogenous
plot(Betadisper.ARGcluster.Staph_RF_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$Staph_RF_predictions, permutations = 999)# p-value = 0.696 - no significant differences in group centroids-  We can conclude that our groups (halves of Staph (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# tetW_RF_predictions
# Betadisper
Betadisper.ARGcluster.tetW_RF_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$tetW_RF_predictions)
Betadisper.ARGcluster.tetW_RF_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.tetW_RF_estimates_HALVES) # p-value = 0.8652 - group dispersions are homogenous
plot(Betadisper.ARGcluster.tetW_RF_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$tetW_RF_predictions, permutations = 999)# p-value = 0.875 - no significant differences in group centroids-  We can conclude that our groups (halves of tetW (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# mecA_RF_predictions
# Betadisper
Betadisper.ARGcluster.mecA_RF_estimates_HALVES <- betadisper(BC.distance.LUR.RF, ARG.cluster.LUR.RF.df_HALVES$mecA_RF_predictions)
Betadisper.ARGcluster.mecA_RF_estimates_HALVES
# Perform an anova using the group dispersions to check for homogeneity of the group dispersions
anova(Betadisper.ARGcluster.mecA_RF_estimates_HALVES) # p-value = 0.5117 - group dispersions are homogenous
plot(Betadisper.ARGcluster.mecA_RF_estimates_HALVES) # Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 
# Use adonis to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df_HALVES$mecA_LUR_estimates, permutations = 999)# p-value - no significant differences in group centroids-  We can conclude that our groups (halves of tetW (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# None significant with data cut in halves either
```
## Ordinations
```{r}
# I will construct ordinations based on modelled microbial agent concentrations
# Read in the ps object which has been agglomerated at the 90% identity level - this was previously created in the script 'BCHRNotebook_20210605'
ARGcluster.aggl.noblanks <- readRDS("C://Users//Cornu003//OneDrive - Universiteit Utrecht//Documents//Epidemiology MSc 2020//Research Project//ResCap//ResCap_2020_v4_rarefied//ARGcluster.aggl.noblanks.rds")

ARGcluster.aggl.noblanks.LUR.RF.estimates <- ARGcluster.aggl.noblanks
sample_data(ARGcluster.aggl.noblanks.LUR.RF.estimates)

# Add the modelled exposure data to the ps object
sample_data(ARGcluster.aggl.noblanks.LUR.RF.estimates) <- sample_data(LUR_RF_residential_predictions)
# Add the copdcaco status to the sample data of the ps object 
ARGcluster.aggl.noblanks.LUR.RF.estimates@sam_data$copdcaco <- ARGcluster.aggl.noblanks@sam_data$copdcaco 
# Check the ps sample data
ARGcluster.aggl.noblanks.LUR.RF.estimates@sam_data


# PCoA 
# I will construct principal coordinates analysis based on Bray-Curtis dissimilarities. These measures are based on abundance or read count data. It generates differences in ARG abundances between two samples (e.g., at species level) which are from 0 to 1 (where 0= both samples share the same species at exactly the same abundances and 1= both samples have complete different species abundances).
# Firstly I need to categorise my exposure variables which are currently continuous numeric to quantiles (factor variables) - I want an equal % of variables in each quantile
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT <- ARGcluster.aggl.noblanks.LUR.RF.estimates
# I will use the quantcut() function in gtools -quantcut(x, q = 4, na.rm = TRUE, ...)
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_LUR_estimates, q=4, labels =c("1st quantile (E.coli_LUR_estimates)", "2nd quantile (E.coli_LUR_estimates)", "3rd quantile (E.coli_LUR_estimates)", "4th quantile (E.coli_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_LUR_estimates, q=4, labels =c("1st quantile (Staph_LUR_estimates)", "2nd quantile (Staph_LUR_estimates)", "3rd quantile (Staph_LUR_estimates)", "4th quantile (Staph_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_LUR_estimates, q=4, labels =c("1st quantile (tetW_LUR_estimates)", "2nd quantile (tetW_LUR_estimates)", "3rd quantile (tetW_LUR_estimates)", "4th quantile (tetW_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_LUR_estimates, q=4, labels =c("1st quantile (mecA_LUR_estimates)", "2nd quantile (mecA_LUR_estimates)", "3rd quantile (mecA_LUR_estimates)", "4th quantile (mecA_LUR_estimates)"))

ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$E.coli_RF_predictions, q=4, labels =c("1st quantile (E.coli_RF_predictions)", "2nd quantile (E.coli_RF_predictions)", "3rd quantile (E.coli_RF_predictions)", "4th quantile (E.coli_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$Staph_RF_predictions, q=4, labels =c("1st quantile (Staph_RF_predictions)", "2nd quantile (Staph_RF_predictions)", "3rd quantile (Staph_RF_predictions)", "4th quantile (Staph_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$tetW_RF_predictions, q=4, labels =c("1st quantile (tetW_RF_predictions)", "2nd quantile (tetW_RF_predictions)", "3rd quantile (tetW_RF_predictions)", "4th quantile (tetW_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_RF_predictions, q=4, labels =c("1st quantile (mecA_RF_predictions)", "2nd quantile (mecA_RF_predictions)", "3rd quantile (mecA_RF_predictions)", "4th quantile (mecA_RF_predictions)"))

# PCoA on the BC dissimilarity matrix of the clustered resistome data (as before)
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA <- ordinate(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, method="PCoA", distance="bray")
# Extract the vectors from the PCoA 
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA$vectors # i.e. this tells us how much of the total variance is explained by each of the axes with respect to the total variance
# Show dominant eigen planes
plot_scree(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA)

# LUR-modelled E. coli
PCoA.plot.E.coli_LUR_estimates<- plot_ordination(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "E.coli_LUR_estimates", shape="E.coli_LUR_estimates") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by E. coli exposure quantiles (LUR-modelled)") +
  labs(legend="E. coli (LUR-modelled) exposure quantiles")+
    geom_point(size =2) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ), size = 2) +
  theme(plot.title = element_text(size = 12))+ # adjusting size of title text
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=15)) + # adjusting size of axis text
  theme(legend.text=element_text(size=10),
        legend.title = element_text(size=10))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 


# LUR-modelled Staph
PCoA.plot.Staph_LUR_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "Staph_LUR_estimates", shape="Staph_LUR_estimates") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by Staph spp. exposure quantiles (LUR-modelled)") +
  labs(legend="Staph (LUR-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = Staph_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.Staph_LUR_estimates
# Add ellipses 
PCoA.plot.Staph_LUR_estimates + stat_ellipse()

# LUR-modelled tetW
PCoA.plot.tetW_LUR_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "tetW_LUR_estimates", shape="tetW_LUR_estimates") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by tetW exposure quantiles (LUR-modelled)") +
  labs(legend="tetW (LUR-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = tetW_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.tetW_LUR_estimates
# Add ellipses 
PCoA.plot.tetW_LUR_estimates + stat_ellipse()


# LUR-modelled mecA
PCoA.plot.mecA_LUR_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "mecA_LUR_estimates", shape="mecA_LUR_estimates") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by mecA exposure quantiles (LUR-modelled)") +
  labs(legend="mecA (LUR-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = mecA_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.mecA_LUR_estimates
# Add ellipses 
PCoA.plot.mecA_LUR_estimates + stat_ellipse()

# RF-modelled E. coli
PCoA.plot.E.coli_RF_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "E.coli_RF_predictions", shape="E.coli_RF_predictions") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by E. coli exposure quantiles (RF-modelled)") +
  labs(legend="E. coli (RF-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.E.coli_RF_estimates
# Add ellipses 
PCoA.plot.E.coli_RF_estimates + stat_ellipse()

# RF-modelled Staph
PCoA.plot.Staph_RF_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "Staph_RF_predictions", shape="Staph_RF_predictions") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by Staph exposure quantiles (RF-modelled)") +
  labs(legend="Staph (RF-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = Staph_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.Staph_RF_estimates
# Add ellipses 
PCoA.plot.Staph_RF_estimates + stat_ellipse()

# RF-modelled tetW
PCoA.plot.tetW_RF_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "tetW_RF_predictions", shape="tetW_RF_predictions") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by tetW exposure quantiles (RF-modelled)") +
  labs(legend="tetW (RF-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = tetW_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.tetW_RF_estimates
# Add ellipses 
PCoA.plot.tetW_RF_estimates + stat_ellipse()

ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data$mecA_RF_predictions
ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA$
# RF-modelled mecA
PCoA.plot.mecA_RF_estimates <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "mecA_RF_predictions", shape="mecA_RF_predictions") +
    ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by mecA exposure quantiles (RF-modelled)") +
  labs(legend="mecA (RF-modelled) exposure quantiles")+
    geom_point(size =5) +
    geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = mecA_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.mecA_RF_estimates
# Add ellipses 
PCoA.plot.mecA_RF_estimates + stat_ellipse()


## CUTTING EXPOSURE DATA INTO HALVES 
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES <- ARGcluster.aggl.noblanks.LUR.RF.estimates
# I will use the quantcut() function in gtools -quantcut(x, q = 4, na.rm = TRUE, ...)
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_LUR_estimates, q=2, labels =c("Top half (E.coli_LUR_estimates)", "Bottom half (E.coli_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_LUR_estimates, q=2, labels =c("Top half (Staph_LUR_estimates)", "Bottom half (Staph_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_LUR_estimates, q=2, labels =c("Top half (tetW_LUR_estimates)", "Bottom half (tetW_LUR_estimates)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_LUR_estimates<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_LUR_estimates, q=2, labels =c("Top half (mecA_LUR_estimates)", "Bottom half (mecA_LUR_estimates)"))

ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$E.coli_RF_predictions, q=2, labels =c("Top half (E.coli_RF_predictions)", "Bottom half (E.coli_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$Staph_RF_predictions, q=2, labels =c("Top half (Staph_RF_predictions)", "Bottom half (Staph_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$tetW_RF_predictions, q=2, labels =c("Top half (tetW_RF_predictions)", "Bottom half (tetW_RF_predictions)"))
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_RF_predictions<-quantcut(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data$mecA_RF_predictions, q=2, labels =c("Top half (mecA_RF_predictions)", "Bottom half (mecA_RF_predictions)"))

# PCoA on the BC dissimilarity matrix of the clustered resistome data (as before)
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA <- ordinate(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, method="PCoA", distance="bray")
# Extract the vectors from the PCoA 
ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA$vectors # i.e. this tells us how much of the total variance is explained by each of the axes with respect to the total variance
# Show dominant eigen planes
plot_scree(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA)

# LUR-modelled E. coli
PCoA.plot.E.coli_LUR_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "E.coli_LUR_estimates", shape="E.coli_LUR_estimates") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by E. coli exposure halves (LUR-modelled)") +
  labs(legend="E. coli (LUR-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.E.coli_LUR_estimates_HALVES
# Add ellipses 
PCoA.plot.E.coli_LUR_estimates_HALVES + stat_ellipse()


# LUR-modelled Staph
PCoA.plot.Staph_LUR_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "Staph_LUR_estimates", shape="Staph_LUR_estimates") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by Staph spp. exposure halves (LUR-modelled)") +
  labs(legend="Staph (LUR-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = Staph_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.Staph_LUR_estimates_HALVES
# Add ellipses 
PCoA.plot.Staph_LUR_estimates_HALVES + stat_ellipse()

# LUR-modelled tetW
PCoA.plot.tetW_LUR_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "tetW_LUR_estimates", shape="tetW_LUR_estimates") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by tetW exposure halves (LUR-modelled)") +
  labs(legend="tetW (LUR-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = tetW_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.tetW_LUR_estimates_HALVES
# Add ellipses 
PCoA.plot.tetW_LUR_estimates_HALVES + stat_ellipse()


# LUR-modelled mecA
PCoA.plot.mecA_LUR_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "mecA_LUR_estimates", shape="mecA_LUR_estimates") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by mecA exposure halves (LUR-modelled)") +
  labs(legend="mecA (LUR-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = mecA_LUR_estimates))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.mecA_LUR_estimates_HALVES
# Add ellipses 
PCoA.plot.mecA_LUR_estimates_HALVES + stat_ellipse()

# RF-modelled E. coli
PCoA.plot.E.coli_RF_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "E.coli_RF_predictions", shape="E.coli_RF_predictions") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by E. coli exposure halves (RF-modelled)") +
  labs(legend="E. coli (RF-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.E.coli_RF_estimates_HALVES
# Add ellipses 
PCoA.plot.E.coli_RF_estimates_HALVES + stat_ellipse()

# RF-modelled Staph
PCoA.plot.Staph_RF_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "Staph_RF_predictions", shape="Staph_RF_predictions") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by Staph exposure halves (RF-modelled)") +
  labs(legend="Staph (RF-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = Staph_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.Staph_RF_estimates_HALVES
# Add ellipses 
PCoA.plot.Staph_RF_estimates_HALVES + stat_ellipse()

# RF-modelled tetW
PCoA.plot.tetW_RF_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "tetW_RF_predictions", shape="tetW_RF_predictions") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by tetW exposure halves (RF-modelled)") +
  labs(legend="tetW (RF-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = tetW_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.tetW_RF_estimates_HALVES
# Add ellipses 
PCoA.plot.tetW_RF_estimates_HALVES + stat_ellipse()


# RF-modelled mecA
PCoA.plot.mecA_RF_estimates_HALVES <- plot_ordination( ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES, ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES.PCoA, color = "mecA_RF_predictions", shape="mecA_RF_predictions") +
  ggtitle("BC PCoA (fully corrected and rarefied ARG counts, 90% identity clustered) - \ncoloured by mecA exposure halves (RF-modelled)") +
  labs(legend="mecA (RF-modelled) exposure halves")+
  geom_point(size =5) +
  geom_text( aes( label=row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.HALVES@sam_data),hjust=-0.3, vjust=-0.5 ) ) +
  theme(plot.title = element_text(size = 13))+ # adjusting size of title text
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10)) + # adjusting size of axis text
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=8))+ # adjusting size of legend text
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = mecA_RF_predictions))# adds ellipses to the PCoA, fills ellipses with colour according to copdcaco status, colour transparency=1/4 of strength 
PCoA.plot.mecA_RF_estimates_HALVES
# Add ellipses 
PCoA.plot.mecA_RF_estimates_HALVES + stat_ellipse()

```
### E. coli PCoA plot for manuscript
```{r}
# E. coli exposure (RF modelled)
set.seed(123)
E.coli_permanova_result <- adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$E.coli_LUR_estimates, permutations = 999)
E.coli_permanova_pval <- E.coli_permanova_result$`Pr(>F)`[1]
# p-value = 0.292 - no significant differences in group centroids-  We can conclude that our groups (quartiles of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# RF-modelled E. coli
PCoA.plot.E.coli_RF_estimates <- plot_ordination(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "E.coli_RF_predictions", shape="E.coli_RF_predictions") +
    ggtitle("Bray-Curtis PCoA - E. coli exposure") +
    labs(legend="E. coli (RF-modelled) exposure quantiles") +
    geom_point(size = 4) +
    geom_text(aes(label = row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data), hjust = -0.3, vjust = -0.5), size = 2) +  # Adjust the size here
    theme(
        plot.title = element_text(size = 12),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)
    ) +
    stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_RF_predictions)) +
    geom_text(x = 0.33, y = -0.5, label = paste("PERMANOVA, p-value =", E.coli_permanova_pval), size = 4, color = "black", family = "Arial") +
    xlab("PCoA1") +
    ylab("PCoA2") +
    coord_fixed(ratio = 1) +
    guides(color = guide_legend(title = "E. coli exposure quantiles"))
PCoA.plot.E.coli_RF_estimates

combined_plot <- PCoA.plot.E.coli_RF_estimates + 
  guides(
    color = guide_legend(
      title = "E. coli exposure quantiles", 
      override.aes = list(shape = 19)
    )
  )

combined_plot

ggsave("Output_files//PCoAs//PCoA.plot.E.coli_RF_estimates.png", PCoA.plot.E.coli_RF_estimates, width = 8, height = 6, dpi = 3000)
```

