# Beta diversity - 90% cluster level
** Tells us how different the microbial composition in one environment is compared to another. I.e. I will look at the whether the microbial composition in COPD pts differs to that in controls.**

## PERMANOVA
```{r}
# There are two tests that are widely used in beta diversity analyses: betadisper and adonis. 
# Betadisper tests whether two or more groups are homogeneously dispersed in relation to their species in studied samples (it is a multivariate analogue of Levene's test for homogeneity of variances). This test can be done to see if one group has more compositional variance than another. Moreover, homogeneity of dispersion among groups is very advisable to have if you want to test if two or more groups have different compositions, which is tested by adonis. So firstly I will perform betadisper: then move onto adonis
# Use betadisper to assess homogeneity of group dispersions - it first calculates the average distance of group members to the group centroid in multivariate space (generated by a distance matrix). Then, an ANOVA is done to test if the dispersions (variances) of groups are different.
#Extract abundance matrix from phyloseq object
ARGclusters.for.beta.div <- as(otu_table(ARGcluster.aggl), "matrix")
# transform into a data frame
ARG.cluster.dataframe <-as.data.frame(ARGclusters.for.beta.div)
ARG.cluster.dataframe
# Calculate BC distances between all sample types
BC.distances <- vegdist(ARG.cluster.dataframe, method =  "bray")
# Add column to dataframe to include Copdcaco status
ARG.cluster.dataframe$copdcaco <- ARGcluster.aggl@sam_data$copdcaco
head(ARG.cluster.dataframe)

# Betadisper 
Betadisper.ARGcluster.copdcontrolblank <- betadisper(BC.distances, ARG.cluster.dataframe$copdcaco)
Betadisper.ARGcluster.copdcontrolblank
# Perform an anova using the group dispersions.
Anova.betadisper.copdcontrolblank <- anova(Betadisper.ARGcluster.copdcontrolblank)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous ("Null hypothesis of no difference in dispersion between groups
Anova.betadisper.copdcontrolblank$`Pr(>F)`# to add to PCoA in above chunk
# make a plot to see our first two PCoA axes to see how our data fits there:
plot(Anova.betadisper.copdcontrolblank)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# PERMANOVA
# Use adonis2 to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
Permanova_results_COPDcontrolblank <- adonis2(BC.distances~ ARG.cluster.dataframe$copdcaco, permutations = 999)
# we see that the groups do  have significantly different compositions (p<0.05). 
# We can conclude that our groups (COPD and control and blank) present homogeneity among group dispersions (compositions vary similarly) but that they have different  compositions.

# Now repeat with no blanks (this is likely the cause of the observed difference in composition)
ARGclusters.for.beta.div <- as(otu_table(ARGcluster.aggl), "matrix")
ARG.cluster.dataframe.noblanks <-as.data.frame(ARGclusters.for.beta.div)[-c(70, 71, 72),] # Remove blanks from the df

# Calculate the BC distances between COPD case and control only
BC.distances.noblanks <- vegdist(ARG.cluster.dataframe.noblanks, method =  "bray")
# Add column to dataframe to include Copdcaco status
ARG.cluster.dataframe.noblanks$copdcaco <- ARGcluster.aggl.noblanks@sam_data$copdcaco
head(ARG.cluster.dataframe.noblanks)

# Betadisper 
Betadisper.ARGcluster.COPDcaco <- betadisper(BC.distances.noblanks, ARG.cluster.dataframe.noblanks$copdcaco)
Betadisper.ARGcluster.COPDcaco
# Perform an anova using the group dispersions.
Anova_betadisper <- anova(Betadisper.ARGcluster.COPDcaco)
# We  see that the ANOVA's p-value is not significant meaning that group dispersions are homogenous ("Null hypothesis of no difference in dispersion between groups
Anova_betadisper$`Pr(>F)`# to add to PCoA in above chunk
# make a plot to see our first two PCoA axes to see how our data fits there:
plot(Betadisper.ARGcluster.COPDcaco)
# Here we see that group dispersions (distances from centroids) are very similar, but also that compositions seem to be very similar too. Let's go to adonis to test whether these compositions are different or not. 

# PERMANOVA
# Use adonis2 to assess compositional dissimilarity - The adonis2() function in the vegan package is an analysis of variance using distance matrices 
set.seed(123)
Permanova_results_COPDcontrol<- adonis2(BC.distances.noblanks~ ARG.cluster.dataframe.noblanks$copdcaco, permutations = 999)
# we see that the groups do not have significantly different compositions (p>0.05). 
# We can conclude that our groups (COPD and control) present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions.
```
### PCoA for manuscript
```{r}
# PCoA for manuscript - COPD case vs control
set.seed(123)
Permanova_results_COPDcontrol <- adonis2(BC.distances.noblanks~ ARG.cluster.dataframe.noblanks$copdcaco, permutations = 999)
Permanova_pval_COPDcontrol <- Permanova_results_COPDcontrol$`Pr(>F)`[1]
# p-value = 0.19 - no significant differences in group centroids-  We can conclude that our groups

# Create PCoA for manuscript
# Firstly I will rename the codes "1", "0" as COPD & control 
ARGcluster.aggl.noblanks@sam_data$copdcaco <- revalue(ARGcluster.aggl.noblanks@sam_data$copdcaco, c('1' ='COPD', '0' = 'control'))

ARGcluster.aggl.PCoA.noblanks.ordination <- ordinate(ARGcluster.aggl.noblanks, method="PCoA", distance="bray")

ARGcluster.aggl.PCoA.plot.noblanks <- plot_ordination(ARGcluster.aggl.noblanks, ARGcluster.aggl.PCoA.noblanks.ordination, color = "copdcaco", shape = "copdcaco") +
  ggtitle("Bray-Curtis PCoA - COPD vs control") +
  labs(legend = "COPD/control status") +
  geom_point(aes(color = copdcaco), size = 4) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  geom_text(aes(label = row.names(ARGcluster.aggl.noblanks@sam_data), hjust = -0.3, vjust = -0.5), size = 2) +
  theme(
    plot.title = element_text(size = 12),
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 15),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10)
  ) +
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = copdcaco, color = copdcaco)) +
  scale_fill_manual(values = c("cornflowerblue", "orange")) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  geom_text(x = 0.42, y = -0.47, label = paste("PERMANOVA, p-value =", Permanova_pval_COPDcontrol), size = 4, color = "black", family = "Arial") +
  xlab("PCoA1") +
  ylab("PCoA2") +
  coord_fixed(ratio = 1) +
  guides(color = guide_legend(title = "Study population"))

ggsave("Output_files//PCoAs//ARGcluster.aggl.PCoA.plot.noblanks.png", ARGcluster.aggl.PCoA.plot.noblanks, width = 8, height = 6, dpi = 3000)



# E. coli exposure
# RF-modelled E. coli
set.seed(123)
E.coli_permanova_result <- adonis2(BC.distance.LUR.RF~ ARG.cluster.LUR.RF.df$E.coli_LUR_estimates, permutations = 999)
E.coli_permanova_pval <- E.coli_permanova_result$`Pr(>F)`[1]
# p-value = 0.292 - no significant differences in group centroids-  We can conclude that our groups (quartiles of e. coli (LUR-modelled) exposure present homogeneity among group dispersions (compositions vary similarly) and also they have very similar compositions (adonis not significant)

# RF-modelled E. coli
PCoA.plot.E.coli_RF_estimates <- plot_ordination(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "E.coli_RF_predictions", shape="E.coli_RF_predictions") +
    ggtitle("Bray-Curtis PCoA - E. coli exposure") +
    labs(legend="E. coli (RF-modelled) exposure quantiles") +
    geom_point(size = 4) +
    geom_text(aes(label = row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data), hjust = -0.3, vjust = -0.5), size = 2) +  # Adjust the size here
    theme(
        plot.title = element_text(size = 12),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)
    ) +
    stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_RF_predictions)) +
    geom_text(x = 0.33, y = -0.5, label = paste("PERMANOVA, p-value =", E.coli_permanova_pval), size = 4, color = "black", family = "Arial") +
    xlab("PCoA1") +
    ylab("PCoA2") +
    coord_fixed(ratio = 1) +
    guides(color = guide_legend(title = "E. coli exposure quantiles"))
PCoA.plot.E.coli_RF_estimates

combined_plot <- PCoA.plot.E.coli_RF_estimates + 
  guides(
    color = guide_legend(
      title = "E. coli exposure quantiles", 
      override.aes = list(shape = 19)
    )
  )

combined_plot


ggsave("Output_files//PCoAs//PCoA.plot.E.coli_RF_estimates.png", PCoA.plot.E.coli_RF_estimates, width = 8, height = 6, dpi = 3000)





PCoA.plot.E.coli_RF_estimates <- plot_ordination(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT, ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT.PCoA, color = "E.coli_RF_predictions", shape = "E.coli_RF_predictions") +
    ggtitle("Bray-Curtis PCoA - E. coli exposure") +
    labs(legend = "E. coli (RF-modelled) exposure quantiles") +
    geom_point(aes(color = E.coli_RF_predictions, shape = E.coli_RF_predictions), size = 4) +
    geom_text(aes(label = row.names(ARGcluster.aggl.noblanks.LUR.RF.estimates.QUANT@sam_data), hjust = -0.3, vjust = -0.5), size = 2) +
    theme(
        plot.title = element_text(size = 12),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)
    ) +
    stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = E.coli_RF_predictions, color = E.coli_RF_predictions)) +
    geom_text(x = 0.33, y = -0.5, label = paste("PERMANOVA, p-value =", E.coli_permanova_pval), size = 4, color = "black", family = "Arial") +
    xlab("PCoA1") +
    ylab("PCoA2") +
    coord_fixed(ratio = 1) +
    scale_color_discrete(name = "E. coli exposure quantiles") +
    scale_shape_discrete(name = "E. coli exposure quantiles") +
    guides(color = guide_legend(override.aes = list(shape = 16)))


```

