---
title: "Multivariable PERMANOVAs - livestock exposure"
output: html_notebook
---

## Multivariable PERMANOVA 
```{r}
#' Multiple Permanovas
#'
#'Function performs individual, \code{\link{adonis}}-style permanovas for every/selected elements of \code{sample_variables(physeq)}
#'
#' @param physeq phyloseq object. A distance matrix is created using \code{otu_table(physeq)}; permanovas are computed for each element of \code{sample_variables(physeq)}
#' @param distm choice of dissimilarity index according to \code{\link{vegdist}}. Options are "manhattan", "euclidean", "canberra", "bray", "kulczynski", "jaccard",
#'              "gower", "altGower", "morisita", "horn", "mountford", "raup" , "binomial", "chao", "cao" or "mahalanobis".
#' @param perms the number of permutations to be performed. Default is 999
#' @param vars Empty=default tests all metadata variables (should be factor levels >=2). Otherwise give a vector c("var1","var2",...etc)
#' @param verbose boolean. Default is TRUE and prints progress.
#' @param terms character vector containing the variable names to be used in a multivariable model formula passed to adonis.
#'
#'
#' @return a dataframe containing p-values of each comparison in the first column, and the number of levels for that variable in the second.
#'
#' @export
#' @import vegan
#' @import phyloseq
#' @note if \code{sample_data(physeq)} contains NAs, the function will convert these to an additional level "none"
#' @note Added the complete adonis output in verbose mode (alex 20200515)
#' @note Added option to specifcy a formula which is passed to the adonis function.  
#'
#' @author Stephanie Jurburg and updated/extended by Alex Bossers \email{alex.bossers@wur.nl} and Warner van Kersen \email{w.vankersen@uu.nl}
#' @examples
#'
#' per <- permanovas(rarefied, "bray")
#'
#'
#'

permanovas_formula <- function(physeq, distm="bray", perms=999, vars="", verbose=TRUE,terms=NULL) {
  
  if( vars[1] == "" ) {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq))), factor))
  } else {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq)[,vars])), factor))
  }
  
  if (physeq@otu_table@taxa_are_rows ==TRUE ) {
    otutab <- t(otu_table(physeq))
  } else {
    otutab <- (otu_table(physeq))
  }
  
  distn <- vegdist(decostand(otutab, "hellinger"), method=distm)
  if(verbose){
    message( paste0("Using Hellinger transformed data and distance metric '",distm,"'") )
  }
  
  
  if(is.null(terms)){ # No terms specified, run univariate permanova's
  
  ADONIS <- matrix(nrow=length(vars), ncol=2)
  row.names(ADONIS) <- colnames(vars)
  colnames(ADONIS) <- c("P.value", "Levels")  
    
  for (i in seq_along (vars)) {
    if (anyNA(vars[[i]])){
      levels(vars[[i]]) <- c(levels(vars[[i]]), "none")
      vars[[i]][is.na(vars[[i]])] <-  "none"
    }
    if ( nlevels(vars[[i]]) == 1 ) {
      message( paste0( "Skipping variable '",rownames(ADONIS)[i],"', not enough levels!") )
      next
    }
    
    adonisResult <- adonis(distn~as.factor(na.pass(vars[[1]])), permutations=perms)
    if(verbose){
      cat(paste0("\nVariable: ",colnames(vars)[i]),"\n")
      print(adonisResult)
      cat("\n\n")
    }
    ADONIS[i,1] <- adonisResult$aov.tab$`Pr(>F)`[1]
    ADONIS[i,2] <- nlevels(vars[[i]])
  }
  return(ADONIS)
  }  
  else{
  # Define formula using terms
  form = reformulate(terms,"distn")
  adonisResult <- adonis(form,data=vars[,names(vars) %in% terms], permutations=perms)
  return(adonisResult)
  }
}

# Run the multivariate PERMANOVA 
# specify terms in the formula
names(ARGcluster.aggl.noblanks.exp@sam_data) # print names of metadata fields 
ARGcluster.aggl.noblanks.exp@sam_data$copdcaco <- ARGcluster.aggl.noblanks@sam_data$copdcaco # add in COPD status into metadata
names(ARGcluster.aggl.noblanks.exp@sam_data)
# "MinDistAnyFarm.NEG","MinDistAnyFarm.INV","AllFarm.3000m","AllFarm.1000m", "AllFarm.500m"                  "AllFarm.250m"                  "npigsWghtDist.1000m.sum","npoultryWghtDist.1000m.sum","ncowsWghtDist.1000m.sum","nhorsesWghtDist.1000m.sum","ngoatsWghtDist.1000m.sum","nsheepWghtDist.1000m.sum","nfuranimsWghtDist.1000m.sum","npigsWghtDist.3000m.sum","npoultryWghtDist.3000m.sum","ncowsWghtDist.3000m.sum","nhorsesWghtDist.3000m.sum","ngoatsWghtDist.3000m.sum","nsheepWghtDist.3000m.sum","nfuranimsWghtDist.3000m.sum","nAnyFarmWghtDist.1000m.sum","nAnyFarmWghtDist.3000m.sum","DISP_EUinPM10_AnnualAv_WP99.5","DISP_PM10CONC_AnnualAv_WP99.5","copdcaco"  
# I don't want to include the fur animals variables so not included in variables and terms parameters
variables_for_multivariable_permanova <- c("MinDistAnyFarm.NEG","MinDistAnyFarm.INV","AllFarm.3000m","AllFarm.1000m","AllFarm.500m","AllFarm.250m","npigsWghtDist.1000m.sum","npoultryWghtDist.1000m.sum","ncowsWghtDist.1000m.sum","nhorsesWghtDist.1000m.sum","ngoatsWghtDist.1000m.sum","nsheepWghtDist.1000m.sum","npigsWghtDist.3000m.sum","npoultryWghtDist.3000m.sum","ncowsWghtDist.3000m.sum","nhorsesWghtDist.3000m.sum","ngoatsWghtDist.3000m.sum","nsheepWghtDist.3000m.sum","nAnyFarmWghtDist.1000m.sum","nAnyFarmWghtDist.3000m.sum","DISP_EUinPM10_AnnualAv_WP99.5","DISP_PM10CONC_AnnualAv_WP99.5","copdcaco")
terms_vector <- c("MinDistAnyFarm.NEG","MinDistAnyFarm.INV","AllFarm.3000m","AllFarm.1000m","AllFarm.500m","AllFarm.250m","npigsWghtDist.1000m.sum","npoultryWghtDist.1000m.sum","ncowsWghtDist.1000m.sum","nhorsesWghtDist.1000m.sum","ngoatsWghtDist.1000m.sum","nsheepWghtDist.1000m.sum","npigsWghtDist.3000m.sum","npoultryWghtDist.3000m.sum","ncowsWghtDist.3000m.sum","nhorsesWghtDist.3000m.sum","ngoatsWghtDist.3000m.sum","nsheepWghtDist.3000m.sum","nAnyFarmWghtDist.1000m.sum","nAnyFarmWghtDist.3000m.sum","DISP_EUinPM10_AnnualAv_WP99.5","DISP_PM10CONC_AnnualAv_WP99.5","copdcaco")

Multivar.permanova <- permanovas_formula(ARGcluster.aggl.noblanks.exp, distm="bray", perms=999, vars=variables_for_multivariable_permanova, verbose=TRUE,terms=terms_vector)

Multivar.permanova <- permanovas_formula(ARGcluster.aggl.noblanks.exp, distm="bray", perms=999,terms=c("MinDistAnyFarm.NEG","MinDistAnyFarm.INV","AllFarm.3000m"))

saveRDS(ARGcluster.aggl.noblanks.exp, "Output_files//Phyloseq_objects//PS_Object_BCH_PERMANOVA")

# Error about colnames received - researched online - try changing adonis function to adonis2 function...
permanovas_formula_adonis2 <- function(physeq, distm="bray", perms=999, vars="", verbose=TRUE,terms=NULL) {
  
  if( vars[1] == "" ) {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq))), factor))
  } else {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq)[,vars])), factor))
  }
  
  if (physeq@otu_table@taxa_are_rows ==TRUE ) {
    otutab <- t(otu_table(physeq))
  } else {
    otutab <- (otu_table(physeq))
  }
  
  distn <- vegdist(decostand(otutab, "hellinger"), method=distm)
  if(verbose){
    message( paste0("Using Hellinger transformed data and distance metric '",distm,"'") )
  }
  
  
  if(is.null(terms)){ # No terms specified, run univariate permanova's
  
  ADONIS <- matrix(nrow=length(vars), ncol=2)
  row.names(ADONIS) <- colnames(vars)
  colnames(ADONIS) <- c("P.value", "Levels")  
    
  for (i in seq_along (vars)) {
    if (anyNA(vars[[i]])){
      levels(vars[[i]]) <- c(levels(vars[[i]]), "none")
      vars[[i]][is.na(vars[[i]])] <-  "none"
    }
    if ( nlevels(vars[[i]]) == 1 ) {
      message( paste0( "Skipping variable '",rownames(ADONIS)[i],"', not enough levels!") )
      next
    }
    
    adonisResult <- adonis2(distn~as.factor(na.pass(vars[[1]])), permutations=perms)
    if(verbose){
      cat(paste0("\nVariable: ",colnames(vars)[i]),"\n")
      print(adonisResult)
      cat("\n\n")
    }
    ADONIS[i,1] <- adonisResult$aov.tab$`Pr(>F)`[1]
    ADONIS[i,2] <- nlevels(vars[[i]])
  }
  return(ADONIS)
  }  
  else{
  # Define formula using terms
  form = reformulate(terms,"distn")
  adonisResult <- adonis2(form,data=vars[,names(vars) %in% terms], permutations=perms)
  return(adonisResult)
  }
}


adonis2_multivar_perm <- permanovas_formula_adonis2(ARGcluster.aggl.noblanks.exp, distm="bray", perms=999, vars=variables_for_multivariable_permanova, verbose=TRUE,terms=terms_vector)
# I now get some output but not what I'm looking for...

# New try - 03/03/2022

factor(ARGcluster.aggl.noblanks.exp@sam_data$)

# make into factors 
# copdcaco and n farms 500m 
# make into factors 
# leave vars section blank
# form - enter formula 
# try new function first of all

permanovas_formula(ARGcluster.aggl.noblanks.exp, distm="bray",vars="copdcaco", perms=999, verbose=TRUE,form=distn~copdcaco)

ARGcluster.aggl.noblanks.exp@sam_data$MinDistAnyFarm.NEG
debug(permanovas_formula)
```
## Bivariable PERMANOVA 
```{r}
#' Multiple Permanovas
#'
#'Function performs individual, \code{\link{adonis}}-style permanovas for every/selected elements of \code{sample_variables(physeq)}
#'
#' @param physeq phyloseq object. A distance matrix is created using \code{otu_table(physeq)}; permanovas are computed for each element of \code{sample_variables(physeq)}
#' @param distm choice of dissimilarity index according to \code{\link{vegdist}}. Options are "manhattan", "euclidean", "canberra", "bray", "kulczynski", "jaccard",
#'              "gower", "altGower", "morisita", "horn", "mountford", "raup" , "binomial", "chao", "cao" or "mahalanobis".
#' @param perms the number of permutations to be performed. Default is 999
#' @param vars Empty=default tests all metadata variables (should be factor levels >=2). Otherwise give a vector c("var1","var2",...etc)
#' @param verbose boolean. Default is TRUE and prints progress.
#' @param terms character vector containing the variable names to be used in a multivariable model formula passed to adonis.
#'
#'
#' @return a dataframe containing p-values of each comparison in the first column, and the number of levels for that variable in the second.
#'
#' @export
#' @import vegan
#' @import phyloseq
#' @note if \code{sample_data(physeq)} contains NAs, the function will convert these to an additional level "none"
#' @note Added the complete adonis output in verbose mode (alex 20200515)
#' @note Added option to specifcy a formula which is passed to the adonis function.  
#'
#' @author Stephanie Jurburg and updated/extended by Alex Bossers \email{alex.bossers@wur.nl} and Warner van Kersen \email{w.vankersen@uu.nl}
#' @examples
#'
#' per <- permanovas(rarefied, "bray")
#'
#'
#'

permanovas_formula <- function(physeq, distm="bray", perms=999, vars="", verbose=TRUE,terms=NULL) {
  
  if( vars[1] == "" ) {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq))), factor))
  } else {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq)[,vars])), factor))
  }
  
  if (physeq@otu_table@taxa_are_rows ==TRUE ) {
    otutab <- t(otu_table(physeq))
  } else {
    otutab <- (otu_table(physeq))
  }
  
  distn <- vegdist(decostand(otutab, "hellinger"), method=distm)
  if(verbose){
    message( paste0("Using Hellinger transformed data and distance metric '",distm,"'") )
  }
  
  
  if(is.null(terms)){ # No terms specified, run univariate permanova's
  
  ADONIS <- matrix(nrow=length(vars), ncol=2)
  row.names(ADONIS) <- colnames(vars)
  colnames(ADONIS) <- c("P.value", "Levels")  
    
  for (i in seq_along (vars)) {
    if (anyNA(vars[[i]])){
      levels(vars[[i]]) <- c(levels(vars[[i]]), "none")
      vars[[i]][is.na(vars[[i]])] <-  "none"
    }
    if ( nlevels(vars[[i]]) == 1 ) {
      message( paste0( "Skipping variable '",rownames(ADONIS)[i],"', not enough levels!") )
      next
    }
    
    adonisResult <- adonis(distn~as.factor(na.pass(vars[[1]])), permutations=perms)
    if(verbose){
      cat(paste0("\nVariable: ",colnames(vars)[i]),"\n")
      print(adonisResult)
      cat("\n\n")
    }
    ADONIS[i,1] <- adonisResult$aov.tab$`Pr(>F)`[1]
    ADONIS[i,2] <- nlevels(vars[[i]])
  }
  return(ADONIS)
  }  
  else{
  # Define formula using terms
  form = reformulate(terms,"distn")
  adonisResult <- adonis(form,data=vars[,names(vars) %in% terms], permutations=perms)
  return(adonisResult)
  }
}

# New version of function that WvK created following issues with the previous one - try with this version first
permanovas_formula2 <- function(physeq, distm="bray", perms=999, vars="", verbose=TRUE,form=NULL) {
  
  if( vars[1] == "" ) {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq))), factor))
  } else {
    vars <- as.data.frame(lapply(as.data.frame(as.matrix(sample_data(physeq)[,vars])), factor))
  }
  
  if (physeq@otu_table@taxa_are_rows ==TRUE ) {
    otutab <- t(otu_table(physeq))
  } else {
    otutab <- (otu_table(physeq))
  }
  
  distn <- vegdist(decostand(otutab, "hellinger"), method=distm)
  if(verbose){
    message( paste0("Using Hellinger transformed data and distance metric '",distm,"'") )
  }
  
  
  if(is.null(form)){ # No terms specified, run univariate permanova's
  
  ADONIS <- matrix(nrow=length(vars), ncol=2)
  row.names(ADONIS) <- colnames(vars)
  colnames(ADONIS) <- c("P.value", "Levels")  
    
  for (i in seq_along (vars)) {
    if (anyNA(vars[[i]])){
      levels(vars[[i]]) <- c(levels(vars[[i]]), "none")
      vars[[i]][is.na(vars[[i]])] <-  "none"
    }
    if ( nlevels(vars[[i]]) == 1 ) {
      message( paste0( "Skipping variable '",rownames(ADONIS)[i],"', not enough levels!") )
      next
    }
    
    adonisResult <- adonis(distn~as.factor(na.pass(vars[[1]])), permutations=perms)
    if(verbose){
      cat(paste0("\nVariable: ",colnames(vars)[i]),"\n")
      print(adonisResult)
      cat("\n\n")
    }
    ADONIS[i,1] <- adonisResult$aov.tab$`Pr(>F)`[1]
    ADONIS[i,2] <- nlevels(vars[[i]])
  }
  return(ADONIS)
  }  
  else{
  # Define formula using terms
  adonisResult <- adonis(form,data=vars[,names(vars) %in% terms], permutations=perms)
  return(adonisResult)
  }
}

# New try - 14/03/2022
ARGcluster.aggl.noblanks.exp.quant@sam_data$copdcaco <- Final.ps.noblanks@sam_data$copdcaco
factor(ARGcluster.aggl.noblanks.exp.quant@sam_data$copdcaco)

# make into factors 
# copdcaco and n farms 500m 
# make into factors 
# leave vars section blank
# form - enter formula 
# try new function first of all

permanovas_formula(ARGcluster.aggl.noblanks.exp.quant, distm="bray",vars="copdcaco", perms=999, verbose=TRUE,form=distn~copdcaco)

# make variable into factor
factor(ARGcluster.aggl.noblanks.exp.quant@sam_data$ngoatsWghtDist.3000m.sum)
2
permanovas_formula2(ARGcluster.aggl.noblanks.exp, distm="bray",vars=c("copdcaco", "ngoatsWghtDist.3000m.sum"), perms=999, verbose=TRUE,form=distn~copdcaco + ngoatsWghtDist.3000m.sum)

permanovas_formula2(ARGcluster.aggl.noblanks.exp, distm="bray", perms=999, verbose=TRUE,form=distn~copdcaco + ngoatsWghtDist.3000m.sum)

undebug(permanovas_formula2)

# All attempts not working

# Will do manually - see chunk above for all adonis functions with copd status included as variable

```