---
title: "6 - Beta diversity"
author: "Beatrice Cornu Hewitt"
date: "`r Sys.time()`"
output: html_document
---
# Libraries
```{r}
library(vegan); library(phyloseq); library(vegan); library(plyr); library(dplyr); library(ggplot2); library(cowplot); library(gtools)
```

# COPD vs control
## PERMANOVA 
```{r}
ps_aggl_noblanks <- readRDS("../Output_files/Phyloseq_objects/6_COPD_resistome_phyloseq_object_rarefied_FPKM_90clustered_noblanks.Rds") # This ps object is gene length corrected but and clustered at the 90% identity level

# Extract abundance matrix from phyloseq object
otu_df <- data.frame(ps_aggl_noblanks@otu_table)
# Calculate BC distances between all sample types
BC <- vegdist(otu_df, method =  "bray")
# Add column to dataframe to include Copdcaco status
otu_df$copdcaco <- ps_aggl_noblanks@sam_data$copdcaco
```
## Check group dispersions
```{r}
# Check group dispersions using betadisper 
Betadisper <- betadisper(BC, otu_df$copdcaco)
# Anova on the group dispersions.
Betadisper.anova <- anova(Betadisper) # group dispersions (distances from centroids) are very similar
Betadisper.anova$`Pr(>F)` # p-value = 0.6355283
plot(Betadisper)

# PERMANOVA
set.seed(123)
permanova_copdcaco <- adonis2(BC ~ otu_df$copdcaco, permutations = 9999)
permanova_copdcaco # R2 = 0.02013, p-value = 0.1922 - no significant compositional differences between COPD case and control
pval_permanova_copdcaco <- permanova_copdcaco$`Pr(>F)`[1] 
pval_permanova_copdcaco_round <- round(pval_permanova_copdcaco, digits = 3) # p-value = 0.192
```
## PCoA ordination
```{r}
ps_aggl_noblanks@sam_data$copdcaco <- revalue(ps_aggl_noblanks@sam_data$copdcaco, c('1' ='COPD', '0' = 'control'))
# PCoA 
ordination <- ordinate(ps_aggl_noblanks, method="PCoA", distance="bray")

# Access the eigenvalues from the ordination object
eigenvalues <- ordination$values
# Calculate the proportion of variance explained by the first 2 PCoA axes
var_explained <- eigenvalues$Eigenvalues[1:2] / sum(eigenvalues$Eigenvalues)
var_explained # Axis 1 = 0.2849242 , Axis 2 = 0.1722990

theme_set(theme_cowplot())
PCoA <- plot_ordination(ps_aggl_noblanks, ordination, color = "copdcaco", shape = "copdcaco") +
  ggtitle("Bray-Curtis PCoA - COPD vs control") +
  labs(legend = "COPD/control status") +
  geom_point(aes(color = copdcaco), size = 4) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  theme(
    plot.title = element_text(size = 12),
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 15),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10)
  ) +
  stat_ellipse(geom = "polygon", alpha = 1/6, aes(fill = copdcaco, color = copdcaco)) +
  scale_fill_manual(values = c("cornflowerblue", "orange")) +
  scale_color_manual(values = c("cornflowerblue", "orange")) +
  geom_text(x = 0.42, y = -0.47, label = paste("R2 = 2%, p-value = 0.19"), size = 4, color = "black", family = "Arial") +
  xlab("PCo1 (28.5%) ") +
  ylab("PCo2 (17.2%)") +
  coord_fixed(ratio = 1) +
  guides(color = guide_legend(title = "Study population"),
         shape = guide_legend(title = "Study population"),
         fill = guide_legend(title = "Study population"))
PCoA
ggsave("../Output_files/PCoAs/PCoA.svg", PCoA, width = 8, height = 6, dpi = 3000)
```

# Livestock exposure
## Prepare data
```{r}
ps_aggl_noblanks_quant <- ps_aggl_noblanks
# Extract the subset of columns from sam_data
sam_data_df <- data.frame(ps_aggl_noblanks_quant@sam_data)

# Define the list of 30 columns to extract for beta analysis
exposure_col_names <- c(
  "MinDistAnyFarm.NEG", "MinDistAnyFarm.INV", "AllFarm.3000m", 
  "AllFarm.1000m", "AllFarm.500m", "AllFarm.250m",
  "npigsWghtDist.1000m.sum", "npoultryWghtDist.1000m.sum",
  "ncowsWghtDist.1000m.sum", "nhorsesWghtDist.1000m.sum",
  "ngoatsWghtDist.1000m.sum", "nsheepWghtDist.1000m.sum",
  "npigsWghtDist.3000m.sum", "npoultryWghtDist.3000m.sum",
  "ncowsWghtDist.3000m.sum", "nhorsesWghtDist.3000m.sum",
  "ngoatsWghtDist.3000m.sum", "nsheepWghtDist.3000m.sum",
  "nAnyFarmWghtDist.1000m.sum", "nAnyFarmWghtDist.3000m.sum",
  "DISP_EUinPM10_AnnualAv_WP99.5", "DISP_PM10CONC_AnnualAv_WP99.5",
  "E.coli_LUR_estimates", "Staph_LUR_estimates", "tetW_LUR_estimates",
  "mecA_LUR_estimates", "E.coli_RF_predictions", "Staph_RF_predictions",
  "tetW_RF_predictions", "mecA_RF_predictions"
)

# Extract the desired columns
exposure_cols <- sam_data_df[, exposure_col_names]
head(exposure_cols)
str(exposure_cols)
# convert all to numeric
for (col in colnames(exposure_cols)) {
  exposure_cols[[col]] <- as.numeric(exposure_cols[[col]])
}

exposure_cols_quant <- exposure_cols

library(gtools) # Ensure gtools is loaded for quantcut

split_into_quantiles_or_halves <- function(x, col_name) {
  # Check if more than a quarter of the values are zeros
  if (sum(x == 0) > length(x) / 4) {
    # Split into halves
    breaks <- 2
    quantile_labels <- paste(c("Low", "High"), " (", col_name, ")", sep = "")
    # Perform the cut, ensuring there are enough unique breaks
    return(cut(x, breaks = breaks, labels = quantile_labels, include.lowest = TRUE))
  } else {
    # Split into quantiles
    breaks <- 4
    # Use quantcut, but check the actual number of levels created
    quant_result <- quantcut(x, q = breaks)
    actual_breaks <- length(levels(quant_result))
    
    # Generate appropriate labels for the actual number of breaks
    quantile_labels <- paste0("Q", 1:actual_breaks, " (", col_name, ")")
    levels(quant_result) <- quantile_labels
    
    return(quant_result)
  }
}

# Loop through each column
for (col in colnames(exposure_cols_quant)) {
  exposure_cols_quant[[col]] <- split_into_quantiles_or_halves(exposure_cols_quant[[col]], col)
}

# Check the result
head(exposure_cols_quant)


# most variables could be split into quartiles but some had too many zeros (more than a quarter were 0) so they were split into high and low categories. 
# Note that the split of these variables is not even like the quantiles
# AllFarm.500m
# AllFarm.250m
# npigsWghtDist.1000m.sum
# npoultryWghtDist.1000m.sum
# ngoatsWghtDist.1000m.sum
# nsheepWghtDist.1000m.sum

# Check the split of a random selection of variables
barchart(exposure_cols_quant$MinDistAnyFarm.NEG)
barchart(exposure_cols_quant$nhorsesWghtDist.1000m.sum)
barchart(exposure_cols_quant$AllFarm.500m)
barchart(exposure_cols_quant$npoultryWghtDist.1000m.sum)


# Ensure the data frame for new sample data is correctly prepared
exposure_cols_quant <- data.frame(exposure_cols_quant) # Convert to data frame if not already

# Check the new data
head(exposure_cols_quant)
str(exposure_cols_quant)

# Update the sample data of the phyloseq object
sample_data(ps_aggl_noblanks_quant) <- sample_data(exposure_cols_quant)

# Check the updated phyloseq object
sample_data(ps_aggl_noblanks_quant)

# Check data structure
str(sample_data(ps_aggl_noblanks_quant))

# Extract abundance matrix from phyloseq object
otu_df <- data.frame(ps_aggl_noblanks_quant@otu_table)
# Calculate BC distances between all sample types
BC <- vegdist(otu_df, method =  "bray")
# Add livestock informations as columns to the otu_df
otu_df$ID <- rownames(otu_df)
exposure_cols_quant$ID <- rownames(exposure_cols_quant)

# Merge the two data frames by the 'ID' column
otu_df_exp <- merge(otu_df, exposure_cols_quant, by = 'ID', all.x = TRUE, suffixes = c("", ""))
otu_df_exp$copdcaco <- ps_aggl_noblanks@sam_data$copdcaco
```
## PERMANOVAs
```{r}
# We conduct several univariable PERMANOVAs separately for each exposure variable
# Then correct p values for multiple testing using BH correction

# List to store adonis results
adonis_results <- list()

# Loop through each variable in exposure_col_names
for (col in exposure_col_names) {
  set.seed(123)
  formula <- as.formula(paste("BC ~ otu_df_exp$", col))
  adonis_result <- adonis2(formula, data = otu_df_exp, permutations = 9999)
  adonis_results[[col]] <- adonis_result
}

# Check the results
adonis_results

# Create an empty data frame to store results
results_df <- data.frame(
  Variable = character(),
  R2 = numeric(),
  P_value = numeric(),
  stringsAsFactors = FALSE
)
# Loop through each variable in exposure_col_names
for (col in exposure_col_names) {
  anova_result <- adonis_results[[col]]
  if (!is.null(anova_result)) {
    R2 <- anova_result$R2[1]
    P_value <- anova_result$"Pr(>F)"[1] 
    if (!(col %in% results_df$Variable)) {
      results_df <- rbind(results_df, data.frame(Variable = col, R2 = R2, P_value = P_value))
    }
  } else {
    print(paste("No ANOVA result for", col))
  }
}

# Adjust p-values using Benjamini-Hochberg correction
results_df$p_adj <- p.adjust(results_df$P_value, method = "BH")

# View the results data frame
results_df

# Change variable names for supplement table
map_names <- function(old_name) {
  new_name <- switch(old_name,
                     "MinDistAnyFarm.NEG" = "Distance to nearest farm (any) (-1*m)",
  "MinDistAnyFarm.INV" = "Distance to nearest farm (any) (m-1)",
  "AllFarm.3000m" = "Number of farms (all) in a 3000m buffer",
  "AllFarm.1000m" = "Number of farms (all) in a 1000m buffer",
  "AllFarm.500m" = "Number of farms (all) in a 500m buffer",
  "AllFarm.250m" = "Number of farms (all) in a 250m buffer",
  "npigsWghtDist.1000m.sum" = "Number of pigs weighted to distance in a 1000m buffer (Σ(N/m))",
  "npoultryWghtDist.1000m.sum" = "Number of poultry weighted to distance in a 1000m buffer (Σ(N/m))",
  "ncowsWghtDist.1000m.sum" = "Number of cows weighted to distance in a 1000m buffer (Σ(N/m))",
  "nhorsesWghtDist.1000m.sum" = "Number of horses weighted to distance in a 1000m buffer (Σ(N/m))",
  "ngoatsWghtDist.1000m.sum" = "Number of goats weighted to distance in a 1000m buffer (Σ(N/m))",
  "nsheepWghtDist.1000m.sum" = "Number of sheep weighted to distance in a 1000m buffer (Σ(N/m))",
  "npigsWghtDist.3000m.sum" = "Number of pigs weighted to distance in a 3000m buffer (Σ(N/m))",
  "npoultryWghtDist.3000m.sum" = "Number of poultry weighted to distance in a 3000m buffer (Σ(N/m))",
  "ncowsWghtDist.3000m.sum" = "Number of cows weighted to distance in a 3000m buffer (Σ(N/m))",
  "nhorsesWghtDist.3000m.sum" = "Number of horses weighted to distance in a 3000m buffer (Σ(N/m))",
  "ngoatsWghtDist.3000m.sum" = "Number of goats weighted to distance in a 3000m buffer (Σ(N/m))",
  "nsheepWghtDist.3000m.sum" = "Number of sheep weighted to distance in a 3000m buffer (Σ(N/m))",
  "nAnyFarmWghtDist.1000m.sum" = "Number of farms (all) weighted to distance in a 1000m buffer (Σ(N/m))",
  "nAnyFarmWghtDist.3000m.sum" = "Number of farms (all) weighted to distance in a 3000m buffer (Σ(N/m))",
  "DISP_EUinPM10_AnnualAv_WP99.5" = "Dispersion-modelled endotoxin concentration (endotoxin units (EU)/m3)",
  "DISP_PM10CONC_AnnualAv_WP99.5" = "Dispersion-modelled PM10 concentration (μg/m3)",
  "E.coli_LUR_estimates" = "LUR-modelled E. coli (copies/m3)",
  "Staph_LUR_estimates" = "LUR-modelled Staphylococcus spp. (copies/m3)",
  "tetW_LUR_estimates" = "LUR-modelled tetW (copies/m3)",
  "mecA_LUR_estimates" = "LUR-modelled mecA (copies/m3)",
  "E.coli_RF_predictions" = "RF-modelled E. coli (copies/m3)",
  "Staph_RF_predictions" = "RF-modelled Staphylococcus spp. (copies/m3)",
  "tetW_RF_predictions" = "RF-modelled tetW (copies/m3)",
  "mecA_RF_predictions" = "RF-modelled mecA (copies/m3)",
                     old_name)
  return(new_name)
}

results_df$Variable <- sapply(results_df$Variable, map_names)
results_df

# Save univariable PERMANOVA results as csv file
write.csv(results_df,"../Output_files/Beta_diversity/permanova_livestock_exposure_results.csv")
```
## Check group dispersions 
```{r}
# Using betadisper
start_col <- 87
end_col <- 117

# Initialize a list to store results
results_list <- list()

# Loop through each column in the specified range
for (i in start_col:end_col) {
  # Extract the current variable name from the column
  var_name <- colnames(otu_df_exp)[i]
  
  # Perform beta dispersion analysis for the current variable
  betadisper_result <- betadisper(BC, otu_df_exp[[var_name]])
  
  # Capture beta dispersion results
  betadisper_summary <- summary(betadisper_result)
  
  # Perform anova to check for homogeneity of the group dispersions
  anova_result <- anova(betadisper_result)
  
  # Capture ANOVA results
  anova_summary <- as.data.frame(anova_result)
  
  # Combine results into a single dataframe
  result_df <- data.frame(
    Variable = var_name,
    ANOVA_PValue = anova_summary$`Pr(>F)`[1]  # Assuming there's only one group dispersion test
  )
  
  # Add the results to the list
  results_list[[var_name]] <- result_df
  
  # Plot the beta dispersion results
  plot(betadisper_result, main = paste("Beta dispersion for", var_name))
}

# Combine all results into a single data frame
results_combined <- do.call(rbind, results_list)

# Save the results to a CSV file
write.csv(results_combined, file = "../Output_files/Beta_diversity/beta_dispersion_results.csv", row.names = FALSE)
```
## PCoA ordinations
```{r}
library(ggplot2)
library(phyloseq)
library(rlang)

# Ensure sample data is correctly set and factor columns
ps_aggl_noblanks_quant@sam_data <- sample_data(otu_df_exp)
ps_aggl_noblanks_quant@sam_data[, 87:117] <- lapply(ps_aggl_noblanks_quant@sam_data[, 87:117], as.factor)

# Extract the subset of sample data
subset_sam_data <- ps_aggl_noblanks_quant@sam_data[, 87:117]
# Convert the subset columns to factors
subset_sam_data[] <- lapply(subset_sam_data, as.factor)
ps_aggl_noblanks_quant_subset <- ps_aggl_noblanks_quant
# Replace the original sample data with the updated subset
ps_aggl_noblanks_quant_subset@sam_data <- subset_sam_data

# Verify the changes
str(ps_aggl_noblanks_quant_subset@sam_data)

# Perform PCoA using Bray-Curtis distances
ARGcluster_PCoA_quant <- ordinate(ps_aggl_noblanks_quant_subset, method = "PCoA", distance = "bray")
# Extract the vectors from the PCoA 
ARGcluster_PCoA_quant$vectors # i.e. the total variance explained by each of the axes with respect to the total variance
# Show dominant eigen planes
plot_scree(ARGcluster_PCoA_quant)
# Initialize list to store plots
plot_list <- list()

# Loop through each variable to create a plot
for (var in names(ps_aggl_noblanks_quant_subset@sam_data)) {
  # Get the PERMANOVA result for the current variable
  result <- results_df[results_df$Variable == map_names(var), ]
  
  # Check if result exists
  if (nrow(result) > 0) {
    # Extract R2 and p-value
    R2 <- result$R2
    p_value <- result$p_adj
    # Format text for annotation
    annotation_text <- paste0("R² = ", round(R2, 2), "\np value = ", format.pval(p_value))
  } else {
    # If no result, use default text
    annotation_text <- "No PERMANOVA result"
  }
  
  # Generate the plot
  p <- plot_ordination(ps_aggl_noblanks_quant_subset, ARGcluster_PCoA_quant, color = var) +
    ggtitle(paste("BC PCoA - coloured by", map_names(var))) +
    geom_point(size = 5, aes(shape = as.factor(ps_aggl_noblanks_quant_subset@sam_data[[var]]))) +  # Ensure shape is mapped to a factor
    stat_ellipse(aes(fill = as.factor(ps_aggl_noblanks_quant_subset@sam_data[[var]])), geom = "polygon", alpha = 0.2) +
    theme(plot.title = element_text(size = 15),  # Adjusting size of title text
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8)) + # Adjusting size of legend text
    annotate("text", x = Inf, y = Inf, label = annotation_text, hjust = 1.1, vjust = 1.1, size = 4, color = "black", fontface = "italic")
  
  # Store the plot in the list
  plot_list[[var]] <- p
  
  # Print the plot
  print(p)
  
  # Uncomment to save each plot
  ggsave(paste0("../Output/Beta_diversity/PCoAs/", var, "_PCoA_plot.png"), plot = p)
}


```
